import type { SecurityRule } from './security.types';

export const DEFAULT_SECURITY_RULES: SecurityRule[] = [
  {
    ruleId: 'rule_https_required',
    type: 'url',
    name: 'HTTPS Required',
    description: 'Block HTTP URLs except localhost',
    pattern: '^http://(?!localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)',
    action: 'block',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_localhost_allow',
    type: 'url',
    name: 'Localhost Allow',
    description: 'Allow localhost URLs for development',
    pattern: '^https?://(localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)(:\\d+)?/',
    action: 'allow',
    severity: 'low',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_ip_address_warn',
    type: 'url',
    name: 'IP Address Warning',
    description: 'Warn on direct IP address access',
    pattern: '^https?://\\d+\\.\\d+\\.\\d+\\.\\d+',
    action: 'warn',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_suspicious_tld',
    type: 'domain',
    name: 'Suspicious TLD',
    description: 'Block suspicious TLDs commonly used in phishing',
    pattern: '\\.(xyz|top|club|online|site|win|bid|work|vip|icu|fun|tech|info)$',
    action: 'warn',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_known_phishing_domains',
    type: 'domain',
    name: 'Known Phishing Domains',
    description: 'Block known phishing domains',
    pattern: '(phishing|fake|scam|fakewallet|metamask|trustwallet|binance)\\.',
    action: 'block',
    severity: 'critical',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_infinite_approval_warn',
    type: 'approval',
    name: 'Infinite Approval Warning',
    description: 'Warn on infinite token approvals',
    pattern: '0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    action: 'warn',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_high_value_approval_warn',
    type: 'approval',
    name: 'High Value Approval Warning',
    description: 'Warn on approval amounts exceeding 1000 ETH equivalent',
    pattern: '',
    action: 'warn',
    severity: 'high',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_dangerous_methods',
    type: 'calldata',
    name: 'Dangerous Methods',
    description: 'Block dangerous contract methods',
    pattern: '(transferOwnership|renounceOwnership|selfdestruct|suicide)',
    action: 'block',
    severity: 'critical',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    ruleId: 'rule_mint_methods',
    type: 'calldata',
    name: 'Mint Methods',
    description: 'Warn on mint methods',
    pattern: '(mint|safeMint|batchMint)',
    action: 'warn',
    severity: 'medium',
    enabled: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const KNOWN_PHISHING_DOMAINS = [
  'phishing-eth.com',
  'metamask-fake.com',
  'trustwallet-scam.com',
  'binance-fake.com',
  'ethereum-phishing.com',
  'open-sea-fake.com',
  'uniswap-scam.com',
  'fake-token-sale.com',
];

export const KNOWN_SAFE_DOMAINS = [
  'metamask.io',
  'trustwallet.com',
  'binance.com',
  'ethereum.org',
  'opensea.io',
  'uniswap.org',
  'coinbase.com',
  'ledger.com',
  'trezor.io',
];

export const SUSPICIOUS_TLDS = [
  'xyz',
  'top',
  'club',
  'online',
  'site',
  'win',
  'bid',
  'work',
  'vip',
  'icu',
  'fun',
  'tech',
  'info',
  'cc',
  'ga',
  'cf',
  'tk',
];

export const DANGEROUS_CONTRACT_METHODS = [
  'transferOwnership',
  'renounceOwnership',
  'selfdestruct',
  'suicide',
  'approve',
  'increaseAllowance',
  'setApprovalForAll',
  'mint',
  'burn',
];

export const HIGH_RISK_CONTRACT_ADDRESSES: Record<string, string[]> = {
  '0x1': ['0x0000000000000000000000000000000000000000'],
};