/**
 * Mock 新闻数据（演示降级用）
 *
 * 设计原则：
 *  - 数据真实（来源名、币种、情绪、时间分布贴近现实）
 *  - 覆盖 BTC / ETH / SOL / BNB 等主流币种
 *  - 时间分布在最近 24 小时内
 *  - 双语字段（原文英文，titleZh 用占位——真实翻译由 Translator 提供）
 *  - 不同情绪（bullish / bearish / neutral）
 *  - 包含 hot / important 标记
 */

import type { NewsItem } from './types';

const NOW = Date.now();
const HOUR = 60 * 60 * 1000;

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'mock-001',
    title: 'Bitcoin surges to new all-time high amid ETF approval speculation',
    titleZh: 'Bitcoin surges to new all-time high amid ETF approval speculation',
    body: 'BTC briefly touched $98,000 as traders bet on a spot ETF approval in Q1, fueling a broad-based rally across major tokens.',
    bodyZh: 'BTC briefly touched $98,000 as traders bet on a spot ETF approval in Q1, fueling a broad-based rally across major tokens.',
    url: 'https://example.com/news/btc-ath',
    source: 'CoinDesk',
    author: 'Jane Doe',
    publishedAt: NOW - 1 * HOUR,
    currencies: ['BTC'],
    categories: ['market'],
    sentiment: 'bullish',
    votes: { like: 312, dislike: 12, comments: 45 },
    imageUrl: 'https://picsum.photos/seed/btc-ath/600/400',
    isHot: true,
    isBullish: true,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-002',
    title: 'Ethereum staking yields hit 4.2% as institutional adoption accelerates',
    titleZh: 'Ethereum staking yields hit 4.2% as institutional adoption accelerates',
    body: 'ETH validators are earning attractive rewards as Lido and Rocket Pool see record TVL from corporate treasuries.',
    bodyZh: 'ETH validators are earning attractive rewards as Lido and Rocket Pool see record TVL from corporate treasuries.',
    url: 'https://example.com/news/eth-staking',
    source: 'Cointelegraph',
    publishedAt: NOW - 2 * HOUR,
    currencies: ['ETH'],
    categories: ['defi'],
    sentiment: 'bullish',
    votes: { like: 198, dislike: 8, comments: 32 },
    isHot: true,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-003',
    title: 'Solana DEX volumes surpass Ethereum for third consecutive week',
    titleZh: 'Solana DEX volumes surpass Ethereum for third consecutive week',
    body: 'SOL-based DEXs processed $9.4B in volume, driven by meme coin activity and Jupiter aggregator growth.',
    bodyZh: 'SOL-based DEXs processed $9.4B in volume, driven by meme coin activity and Jupiter aggregator growth.',
    url: 'https://example.com/news/sol-dex',
    source: 'The Block',
    publishedAt: NOW - 3 * HOUR,
    currencies: ['SOL'],
    categories: ['defi'],
    sentiment: 'bullish',
    votes: { like: 156, dislike: 5, comments: 21 },
    isHot: true,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-004',
    title: 'BNB Chain announces $1B ecosystem fund for builders',
    titleZh: 'BNB Chain announces $1B ecosystem fund for builders',
    body: 'The fund will support DeFi, gaming and infrastructure projects over the next 4 years, with a focus on emerging markets.',
    bodyZh: 'The fund will support DeFi, gaming and infrastructure projects over the next 4 years, with a focus on emerging markets.',
    url: 'https://example.com/news/bnb-fund',
    source: 'Decrypt',
    publishedAt: NOW - 4 * HOUR,
    currencies: ['BNB'],
    categories: ['technology'],
    sentiment: 'bullish',
    votes: { like: 89, dislike: 3, comments: 12 },
    isHot: false,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-005',
    title: 'SEC charges major crypto exchange with securities violations',
    titleZh: 'SEC charges major crypto exchange with securities violations',
    body: 'The regulator alleges the platform operated as an unregistered exchange, broker and clearing agency.',
    bodyZh: 'The regulator alleges the platform operated as an unregistered exchange, broker and clearing agency.',
    url: 'https://example.com/news/sec-charge',
    source: 'Reuters',
    publishedAt: NOW - 5 * HOUR,
    currencies: ['BTC', 'ETH'],
    categories: ['regulation'],
    sentiment: 'bearish',
    votes: { like: 45, dislike: 234, comments: 89 },
    isHot: true,
    isBullish: false,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-006',
    title: 'Crypto market crashes 12% as Bitcoin drops below $80,000',
    titleZh: 'Crypto market crashes 12% as Bitcoin drops below $80,000',
    body: 'A wave of liquidations totaling $1.2B swept the market as BTC broke key support levels amid regulator pressure.',
    bodyZh: 'A wave of liquidations totaling $1.2B swept the market as BTC broke key support levels amid regulator pressure.',
    url: 'https://example.com/news/market-crash',
    source: 'Bloomberg',
    publishedAt: NOW - 6 * HOUR,
    currencies: ['BTC', 'ETH', 'SOL', 'BNB'],
    categories: ['market'],
    sentiment: 'bearish',
    votes: { like: 22, dislike: 312, comments: 156 },
    isHot: true,
    isBullish: false,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-007',
    title: 'NFT trading volume rebounds with $128M weekly sales',
    titleZh: 'NFT trading volume rebounds with $128M weekly sales',
    body: 'Ethereum and Bitcoin Ordinals led the recovery as collections like Pudgy Penguins saw renewed interest.',
    bodyZh: 'Ethereum and Bitcoin Ordinals led the recovery as collections like Pudgy Penguins saw renewed interest.',
    url: 'https://example.com/news/nft-rebound',
    source: 'CoinDesk',
    publishedAt: NOW - 7 * HOUR,
    currencies: ['ETH', 'BTC'],
    categories: ['nft'],
    sentiment: 'neutral',
    votes: { like: 78, dislike: 21, comments: 18 },
    isHot: false,
    isBullish: false,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-008',
    title: 'Bitcoin mining difficulty reaches record 102.3T',
    titleZh: 'Bitcoin mining difficulty reaches record 102.3T',
    body: 'The network hashrate continues to climb as new ASIC miners come online in the US and Paraguay.',
    bodyZh: 'The network hashrate continues to climb as new ASIC miners come online in the US and Paraguay.',
    url: 'https://example.com/news/mining-difficulty',
    source: 'The Block',
    publishedAt: NOW - 8 * HOUR,
    currencies: ['BTC'],
    categories: ['mining'],
    sentiment: 'neutral',
    votes: { like: 67, dislike: 4, comments: 11 },
    isHot: false,
    isBullish: false,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-009',
    title: 'BlackRock spot Ethereum ETF sees record $312M daily inflow',
    titleZh: 'BlackRock spot Ethereum ETF sees record $312M daily inflow',
    body: 'Institutional demand for ETH exposure continues to grow, with $ETH ETFs attracting $2.1B in the past month.',
    bodyZh: 'Institutional demand for ETH exposure continues to grow, with $ETH ETFs attracting $2.1B in the past month.',
    url: 'https://example.com/news/eth-etf-inflow',
    source: 'Cointelegraph',
    publishedAt: NOW - 9 * HOUR,
    currencies: ['ETH'],
    categories: ['market', 'regulation'],
    sentiment: 'bullish',
    votes: { like: 245, dislike: 11, comments: 38 },
    isHot: true,
    isBullish: true,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-010',
    title: 'DeFi protocol suffers $45M exploit, plunging TVL by 38%',
    titleZh: 'DeFi protocol suffers $45M exploit, plunging TVL by 38%',
    body: 'A reentrancy bug allowed the attacker to drain lending pools, prompting withdrawals across similar platforms.',
    bodyZh: 'A reentrancy bug allowed the attacker to drain lending pools, prompting withdrawals across similar platforms.',
    url: 'https://example.com/news/defi-exploit',
    source: 'PeckShield',
    publishedAt: NOW - 10 * HOUR,
    currencies: ['ETH'],
    categories: ['defi'],
    sentiment: 'bearish',
    votes: { like: 18, dislike: 189, comments: 67 },
    isHot: true,
    isBullish: false,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-011',
    title: 'Coinbase reports Q4 revenue beat, sees $2.3B in trading volume',
    titleZh: 'Coinbase reports Q4 revenue beat, sees $2.3B in trading volume',
    body: 'The exchange credited stronger retail activity and new product launches for the quarterly surge.',
    bodyZh: 'The exchange credited stronger retail activity and new product launches for the quarterly surge.',
    url: 'https://example.com/news/coinbase-earnings',
    source: 'CNBC',
    publishedAt: NOW - 11 * HOUR,
    currencies: ['BTC', 'ETH'],
    categories: ['market'],
    sentiment: 'bullish',
    votes: { like: 134, dislike: 7, comments: 24 },
    isHot: false,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-012',
    title: 'EU MiCA framework enters full force, impacting stablecoin issuers',
    titleZh: 'EU MiCA framework enters full force, impacting stablecoin issuers',
    body: 'Crypto firms operating in the EU must now comply with new licensing, reserve and disclosure requirements.',
    bodyZh: 'Crypto firms operating in the EU must now comply with new licensing, reserve and disclosure requirements.',
    url: 'https://example.com/news/mica-effective',
    source: 'Reuters',
    publishedAt: NOW - 12 * HOUR,
    currencies: ['USDT', 'USDC'],
    categories: ['regulation'],
    sentiment: 'neutral',
    votes: { like: 56, dislike: 23, comments: 28 },
    isHot: false,
    isBullish: false,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-013',
    title: 'XRP rallies 18% on renewed optimism in SEC lawsuit',
    titleZh: 'XRP rallies 18% on renewed optimism in SEC lawsuit',
    body: 'Traders anticipate a favorable settlement after recent court filings cited a "fair notice" defense.',
    bodyZh: 'Traders anticipate a favorable settlement after recent court filings cited a "fair notice" defense.',
    url: 'https://example.com/news/xrp-rally',
    source: 'CoinDesk',
    publishedAt: NOW - 13 * HOUR,
    currencies: ['XRP'],
    categories: ['market', 'regulation'],
    sentiment: 'bullish',
    votes: { like: 187, dislike: 9, comments: 31 },
    isHot: true,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-014',
    title: 'Cardano launches first Bitcoin DeFi bridge, unlocking $1.4B liquidity',
    titleZh: 'Cardano launches first Bitcoin DeFi bridge, unlocking $1.4B liquidity',
    body: 'The new bridge enables BTC holders to participate in Cardano lending and yield farming protocols.',
    bodyZh: 'The new bridge enables BTC holders to participate in Cardano lending and yield farming protocols.',
    url: 'https://example.com/news/ada-bridge',
    source: 'Decrypt',
    publishedAt: NOW - 14 * HOUR,
    currencies: ['ADA', 'BTC'],
    categories: ['defi', 'technology'],
    sentiment: 'bullish',
    votes: { like: 95, dislike: 6, comments: 19 },
    isHot: false,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-015',
    title: 'Bitcoin halving countdown: 89 days away, miners prepare for difficulty reset',
    titleZh: 'Bitcoin halving countdown: 89 days away, miners prepare for difficulty reset',
    body: 'The halving will cut block rewards from 6.25 BTC to 3.125 BTC, with historical patterns pointing to a bull cycle.',
    bodyZh: 'The halving will cut block rewards from 6.25 BTC to 3.125 BTC, with historical patterns pointing to a bull cycle.',
    url: 'https://example.com/news/btc-halving',
    source: 'Bitcoin Magazine',
    publishedAt: NOW - 15 * HOUR,
    currencies: ['BTC'],
    categories: ['mining', 'market'],
    sentiment: 'neutral',
    votes: { like: 142, dislike: 8, comments: 27 },
    isHot: false,
    isBullish: false,
    isImportant: true,
    origin: 'mock',
  },
  {
    id: 'mock-016',
    title: 'Dogecoin surges 22% on payment integration announcement',
    titleZh: 'Dogecoin surges 22% on payment integration announcement',
    body: 'A major merchant network will begin accepting DOGE, sending the meme coin to multi-month highs.',
    bodyZh: 'A major merchant network will begin accepting DOGE, sending the meme coin to multi-month highs.',
    url: 'https://example.com/news/doge-pump',
    source: 'CoinTelegraph',
    publishedAt: NOW - 16 * HOUR,
    currencies: ['DOGE'],
    categories: ['market'],
    sentiment: 'bullish',
    votes: { like: 198, dislike: 14, comments: 43 },
    isHot: true,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-017',
    title: 'Polygon zkEVM upgrade reduces gas fees by 90%',
    titleZh: 'Polygon zkEVM upgrade reduces gas fees by 90%',
    body: 'The latest hard fork slashes transaction costs, making Polygon one of the cheapest L2 networks for retail users.',
    bodyZh: 'The latest hard fork slashes transaction costs, making Polygon one of the cheapest L2 networks for retail users.',
    url: 'https://example.com/news/polygon-zkevm',
    source: 'The Block',
    publishedAt: NOW - 17 * HOUR,
    currencies: ['MATIC'],
    categories: ['technology'],
    sentiment: 'bullish',
    votes: { like: 78, dislike: 3, comments: 14 },
    isHot: false,
    isBullish: true,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-018',
    title: 'Major exchange delists 5 altcoins citing regulatory uncertainty',
    titleZh: 'Major exchange delists 5 altcoins citing regulatory uncertainty',
    body: 'The platform cited "evolving regulatory landscape" as the reason for removing the tokens from spot trading.',
    bodyZh: 'The platform cited "evolving regulatory landscape" as the reason for removing the tokens from spot trading.',
    url: 'https://example.com/news/delisting',
    source: 'Bloomberg',
    publishedAt: NOW - 18 * HOUR,
    currencies: ['XRP', 'ADA', 'DOT'],
    categories: ['regulation'],
    sentiment: 'bearish',
    votes: { like: 34, dislike: 167, comments: 52 },
    isHot: true,
    isBullish: false,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-019',
    title: 'Stablecoin issuer launches on Tron network to capture emerging market demand',
    titleZh: 'Stablecoin issuer launches on Tron network to capture emerging market demand',
    body: 'TRC-20 version of the stablecoin offers faster settlement and lower fees for cross-border payments.',
    bodyZh: 'TRC-20 version of the stablecoin offers faster settlement and lower fees for cross-border payments.',
    url: 'https://example.com/news/stablecoin-tron',
    source: 'Decrypt',
    publishedAt: NOW - 19 * HOUR,
    currencies: ['TRX', 'USDT'],
    categories: ['defi', 'technology'],
    sentiment: 'neutral',
    votes: { like: 67, dislike: 5, comments: 13 },
    isHot: false,
    isBullish: false,
    isImportant: false,
    origin: 'mock',
  },
  {
    id: 'mock-020',
    title: 'Ethereum L2 networks see combined TVL exceed $20B for first time',
    titleZh: 'Ethereum L2 networks see combined TVL exceed $20B for first time',
    body: 'Arbitrum, Optimism and Base lead the charge as users seek cheaper transactions for DeFi activity.',
    bodyZh: 'Arbitrum, Optimism and Base lead the charge as users seek cheaper transactions for DeFi activity.',
    url: 'https://example.com/news/l2-tvl',
    source: 'Cointelegraph',
    publishedAt: NOW - 20 * HOUR,
    currencies: ['ETH'],
    categories: ['defi', 'technology'],
    sentiment: 'bullish',
    votes: { like: 156, dislike: 4, comments: 22 },
    isHot: true,
    isBullish: true,
    isImportant: true,
    origin: 'mock',
  },
];
