import type { VcTemplate } from '../vc-issue.types';

export const COMMERCE_VC_TEMPLATES: VcTemplate[] = [
  {
    templateId: 'MerchantCredential',
    name: 'Merchant Credential',
    description: 'Verifies that the holder is a registered merchant',
    type: 'MerchantCredential',
    schemaId: 'https://stockexchange.io/schemas/merchant-credential/v1',
    format: 'jsonld',
    claims: [
      { name: 'merchantId', type: 'string', required: true, description: 'Unique merchant identifier' },
      { name: 'businessName', type: 'string', required: true, description: 'Business name' },
      { name: 'registrationDate', type: 'string', required: true, description: 'Date when the merchant was registered' },
      { name: 'verified', type: 'boolean', required: true, description: 'Whether the merchant is verified' },
      { name: 'country', type: 'string', required: false, description: 'Country of business registration' },
      { name: 'industry', type: 'string', required: false, description: 'Industry category' },
      { name: 'rating', type: 'number', required: false, description: 'Merchant rating', validation: { min: 0, max: 5 } },
    ],
    requiredClaims: ['merchantId', 'businessName', 'registrationDate', 'verified'],
    optionalClaims: ['country', 'industry', 'rating'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'ProductAuthenticityCredential',
    name: 'Product Authenticity Credential',
    description: 'Verifies the authenticity of a product',
    type: 'ProductAuthenticityCredential',
    schemaId: 'https://stockexchange.io/schemas/product-authenticity/v1',
    format: 'jsonld',
    claims: [
      { name: 'productId', type: 'string', required: true, description: 'Unique product identifier' },
      { name: 'productName', type: 'string', required: true, description: 'Product name' },
      { name: 'manufacturer', type: 'string', required: true, description: 'Manufacturer name' },
      { name: 'manufactureDate', type: 'string', required: true, description: 'Date of manufacture' },
      { name: 'origin', type: 'string', required: true, description: 'Country of origin' },
      { name: 'serialNumber', type: 'string', required: false, description: 'Product serial number' },
      { name: 'certifications', type: 'string[]', required: false, description: 'List of certifications' },
    ],
    requiredClaims: ['productId', 'productName', 'manufacturer', 'manufactureDate', 'origin'],
    optionalClaims: ['serialNumber', 'certifications'],
    defaultExpirationDays: 730,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'SupplyChainCredential',
    name: 'Supply Chain Credential',
    description: 'Verifies supply chain information for a product',
    type: 'SupplyChainCredential',
    schemaId: 'https://stockexchange.io/schemas/supply-chain/v1',
    format: 'jsonld',
    claims: [
      { name: 'productId', type: 'string', required: true, description: 'Unique product identifier' },
      { name: 'currentLocation', type: 'string', required: true, description: 'Current location of the product' },
      { name: 'status', type: 'string', required: true, description: 'Supply chain status', validation: { enum: ['in_transit', 'warehouse', 'delivered', 'processing'] } },
      { name: 'lastUpdate', type: 'string', required: true, description: 'Last update timestamp' },
      { name: 'originLocation', type: 'string', required: false, description: 'Origin location' },
      { name: 'destinationLocation', type: 'string', required: false, description: 'Destination location' },
      { name: 'carrier', type: 'string', required: false, description: 'Carrier company' },
      { name: 'trackingNumber', type: 'string', required: false, description: 'Tracking number' },
    ],
    requiredClaims: ['productId', 'currentLocation', 'status', 'lastUpdate'],
    optionalClaims: ['originLocation', 'destinationLocation', 'carrier', 'trackingNumber'],
    defaultExpirationDays: 30,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];