import type { VcTemplate } from '../vc-issue.types';

export const EXCHANGE_VC_TEMPLATES: VcTemplate[] = [
  {
    templateId: 'TradingCredential',
    name: 'Trading Credential',
    description: 'Verifies that the holder is a registered trader on the exchange',
    type: 'TradingCredential',
    schemaId: 'https://stockexchange.io/schemas/trading-credential/v1',
    format: 'jsonld',
    claims: [
      { name: 'traderId', type: 'string', required: true, description: 'Unique trader identifier' },
      { name: 'accountType', type: 'string', required: true, description: 'Account type: basic, premium, institutional', validation: { enum: ['basic', 'premium', 'institutional'] } },
      { name: 'registrationDate', type: 'string', required: true, description: 'Date when the account was registered' },
      { name: 'verified', type: 'boolean', required: true, description: 'Whether the account is verified' },
      { name: 'tradingVolume', type: 'string', required: false, description: 'Total trading volume in USD' },
      { name: 'kycLevel', type: 'number', required: false, description: 'KYC verification level', validation: { min: 0, max: 3 } },
    ],
    requiredClaims: ['traderId', 'accountType', 'registrationDate', 'verified'],
    optionalClaims: ['tradingVolume', 'kycLevel'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'KycCredential',
    name: 'KYC Credential',
    description: 'Verifies that the holder has completed KYC verification',
    type: 'KycCredential',
    schemaId: 'https://stockexchange.io/schemas/kyc-credential/v1',
    format: 'jsonld',
    claims: [
      { name: 'kycLevel', type: 'number', required: true, description: 'KYC verification level', validation: { min: 1, max: 3 } },
      { name: 'verifiedAt', type: 'string', required: true, description: 'Date when KYC was verified' },
      { name: 'expirationDate', type: 'string', required: true, description: 'Date when KYC expires' },
      { name: 'documentType', type: 'string', required: false, description: 'Type of document used for verification', validation: { enum: ['passport', 'national_id', 'driver_license'] } },
      { name: 'country', type: 'string', required: false, description: 'Country of residence' },
    ],
    requiredClaims: ['kycLevel', 'verifiedAt', 'expirationDate'],
    optionalClaims: ['documentType', 'country'],
    defaultExpirationDays: 180,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'StakingCredential',
    name: 'Staking Credential',
    description: 'Verifies staking participation and rewards',
    type: 'StakingCredential',
    schemaId: 'https://stockexchange.io/schemas/staking-credential/v1',
    format: 'jsonld',
    claims: [
      { name: 'stakingAmount', type: 'string', required: true, description: 'Amount staked in native tokens' },
      { name: 'stakingStartDate', type: 'string', required: true, description: 'Date when staking started' },
      { name: 'stakingEndDate', type: 'string', required: false, description: 'Date when staking ends' },
      { name: 'apy', type: 'string', required: false, description: 'Annual percentage yield' },
      { name: 'rewardsEarned', type: 'string', required: false, description: 'Total rewards earned' },
      { name: 'validator', type: 'string', required: false, description: 'Validator address' },
    ],
    requiredClaims: ['stakingAmount', 'stakingStartDate'],
    optionalClaims: ['stakingEndDate', 'apy', 'rewardsEarned', 'validator'],
    defaultExpirationDays: 90,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'LiquidityProviderCredential',
    name: 'Liquidity Provider Credential',
    description: 'Verifies liquidity provision on DEX pools',
    type: 'LiquidityProviderCredential',
    schemaId: 'https://stockexchange.io/schemas/lp-credential/v1',
    format: 'jsonld',
    claims: [
      { name: 'poolAddress', type: 'string', required: true, description: 'DEX pool address' },
      { name: 'tokenA', type: 'string', required: true, description: 'First token in the pair' },
      { name: 'tokenB', type: 'string', required: true, description: 'Second token in the pair' },
      { name: 'liquidityAmount', type: 'string', required: true, description: 'Amount of liquidity provided' },
      { name: 'lpTokenBalance', type: 'string', required: true, description: 'LP token balance' },
      { name: 'feesEarned', type: 'string', required: false, description: 'Total fees earned' },
      { name: 'providerSince', type: 'string', required: false, description: 'Date since providing liquidity' },
    ],
    requiredClaims: ['poolAddress', 'tokenA', 'tokenB', 'liquidityAmount', 'lpTokenBalance'],
    optionalClaims: ['feesEarned', 'providerSince'],
    defaultExpirationDays: 30,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];