import type { VcTemplate } from '../vc-issue.types';

export const FINANCIAL_VC_TEMPLATES: VcTemplate[] = [
  {
    templateId: 'CreditScoreCredential',
    name: 'Credit Score Credential',
    description: 'Verifies credit score information',
    type: 'CreditScoreCredential',
    schemaId: 'https://stockexchange.io/schemas/credit-score/v1',
    format: 'jsonld',
    claims: [
      { name: 'score', type: 'number', required: true, description: 'Credit score', validation: { min: 300, max: 850 } },
      { name: 'provider', type: 'string', required: true, description: 'Credit score provider' },
      { name: 'calculatedAt', type: 'string', required: true, description: 'Date when score was calculated' },
      { name: 'scoreRange', type: 'string', required: false, description: 'Score range', validation: { enum: ['poor', 'fair', 'good', 'very_good', 'excellent'] } },
      { name: 'factors', type: 'string[]', required: false, description: 'Factors affecting the score' },
    ],
    requiredClaims: ['score', 'provider', 'calculatedAt'],
    optionalClaims: ['scoreRange', 'factors'],
    defaultExpirationDays: 90,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'IncomeCredential',
    name: 'Income Credential',
    description: 'Verifies income information',
    type: 'IncomeCredential',
    schemaId: 'https://stockexchange.io/schemas/income/v1',
    format: 'jsonld',
    claims: [
      { name: 'amount', type: 'string', required: true, description: 'Income amount in USD' },
      { name: 'frequency', type: 'string', required: true, description: 'Income frequency', validation: { enum: ['monthly', 'yearly', 'weekly'] } },
      { name: 'source', type: 'string', required: true, description: 'Income source' },
      { name: 'verifiedAt', type: 'string', required: true, description: 'Date when income was verified' },
      { name: 'currency', type: 'string', required: false, description: 'Currency code', validation: { enum: ['USD', 'EUR', 'GBP', 'CNY'] } },
    ],
    requiredClaims: ['amount', 'frequency', 'source', 'verifiedAt'],
    optionalClaims: ['currency'],
    defaultExpirationDays: 180,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'InsuranceCredential',
    name: 'Insurance Credential',
    description: 'Verifies insurance coverage',
    type: 'InsuranceCredential',
    schemaId: 'https://stockexchange.io/schemas/insurance/v1',
    format: 'jsonld',
    claims: [
      { name: 'policyNumber', type: 'string', required: true, description: 'Policy number' },
      { name: 'insuranceType', type: 'string', required: true, description: 'Type of insurance', validation: { enum: ['health', 'life', 'property', 'travel', 'auto'] } },
      { name: 'provider', type: 'string', required: true, description: 'Insurance provider' },
      { name: 'coverageAmount', type: 'string', required: true, description: 'Coverage amount' },
      { name: 'startDate', type: 'string', required: true, description: 'Policy start date' },
      { name: 'endDate', type: 'string', required: true, description: 'Policy end date' },
      { name: 'status', type: 'string', required: false, description: 'Policy status', validation: { enum: ['active', 'expired', 'cancelled'] } },
    ],
    requiredClaims: ['policyNumber', 'insuranceType', 'provider', 'coverageAmount', 'startDate', 'endDate'],
    optionalClaims: ['status'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];