import type { VcTemplate } from '../vc-issue.types';

export const GAMING_VC_TEMPLATES: VcTemplate[] = [
  {
    templateId: 'PlayerCredential',
    name: 'Player Credential',
    description: 'Verifies that the holder is a registered game player',
    type: 'PlayerCredential',
    schemaId: 'https://stockexchange.io/schemas/player-credential/v1',
    format: 'jsonld',
    claims: [
      { name: 'playerId', type: 'string', required: true, description: 'Unique player identifier' },
      { name: 'username', type: 'string', required: true, description: 'Player username' },
      { name: 'registrationDate', type: 'string', required: true, description: 'Date when the player registered' },
      { name: 'level', type: 'number', required: false, description: 'Player level', validation: { min: 1 } },
      { name: 'rank', type: 'string', required: false, description: 'Player rank' },
      { name: 'achievements', type: 'string[]', required: false, description: 'List of achievements' },
    ],
    requiredClaims: ['playerId', 'username', 'registrationDate'],
    optionalClaims: ['level', 'rank', 'achievements'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'ItemOwnershipCredential',
    name: 'Item Ownership Credential',
    description: 'Verifies ownership of a game item',
    type: 'ItemOwnershipCredential',
    schemaId: 'https://stockexchange.io/schemas/item-ownership/v1',
    format: 'jsonld',
    claims: [
      { name: 'itemId', type: 'string', required: true, description: 'Unique item identifier' },
      { name: 'itemName', type: 'string', required: true, description: 'Item name' },
      { name: 'itemType', type: 'string', required: true, description: 'Item type', validation: { enum: ['weapon', 'armor', 'consumable', 'crafting', 'collectible'] } },
      { name: 'rarity', type: 'string', required: true, description: 'Item rarity', validation: { enum: ['common', 'uncommon', 'rare', 'epic', 'legendary'] } },
      { name: 'quantity', type: 'number', required: true, description: 'Quantity owned', validation: { min: 1 } },
      { name: 'acquiredAt', type: 'string', required: false, description: 'Date when acquired' },
      { name: 'metadata', type: 'object', required: false, description: 'Additional item metadata' },
    ],
    requiredClaims: ['itemId', 'itemName', 'itemType', 'rarity', 'quantity'],
    optionalClaims: ['acquiredAt', 'metadata'],
    defaultExpirationDays: 0,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'AchievementCredential',
    name: 'Achievement Credential',
    description: 'Verifies that the holder has earned an achievement',
    type: 'AchievementCredential',
    schemaId: 'https://stockexchange.io/schemas/achievement/v1',
    format: 'jsonld',
    claims: [
      { name: 'achievementId', type: 'string', required: true, description: 'Unique achievement identifier' },
      { name: 'achievementName', type: 'string', required: true, description: 'Achievement name' },
      { name: 'description', type: 'string', required: false, description: 'Achievement description' },
      { name: 'earnedAt', type: 'string', required: true, description: 'Date when earned' },
      { name: 'rarity', type: 'string', required: false, description: 'Achievement rarity', validation: { enum: ['common', 'uncommon', 'rare', 'epic', 'legendary'] } },
      { name: 'points', type: 'number', required: false, description: 'Points awarded', validation: { min: 0 } },
    ],
    requiredClaims: ['achievementId', 'achievementName', 'earnedAt'],
    optionalClaims: ['description', 'rarity', 'points'],
    defaultExpirationDays: 0,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];