import type { VcTemplate } from '../vc-issue.types';

export const SAMOA_ENTERPRISE_VC_TEMPLATES: VcTemplate[] = [
  {
    templateId: 'EnterpriseRegistrationCredential',
    name: 'Enterprise Registration Credential',
    description: 'Verifies that the enterprise is registered in Samoa',
    type: 'EnterpriseRegistrationCredential',
    schemaId: 'https://stockexchange.io/schemas/enterprise-registration/v1',
    format: 'jsonld',
    claims: [
      { name: 'companyName', type: 'string', required: true, description: 'Company name' },
      { name: 'registrationNumber', type: 'string', required: true, description: 'Registration number' },
      { name: 'registeredAt', type: 'string', required: true, description: 'Date when registered' },
      { name: 'companyType', type: 'string', required: true, description: 'Company type', validation: { enum: ['private', 'public', 'partnership', 'sole_trader'] } },
      { name: 'businessActivity', type: 'string', required: false, description: 'Primary business activity' },
      { name: 'registeredAddress', type: 'string', required: false, description: 'Registered address' },
    ],
    requiredClaims: ['companyName', 'registrationNumber', 'registeredAt', 'companyType'],
    optionalClaims: ['businessActivity', 'registeredAddress'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'TaxComplianceCredential',
    name: 'Tax Compliance Credential',
    description: 'Verifies tax compliance status',
    type: 'TaxComplianceCredential',
    schemaId: 'https://stockexchange.io/schemas/tax-compliance/v1',
    format: 'jsonld',
    claims: [
      { name: 'taxId', type: 'string', required: true, description: 'Tax identification number' },
      { name: 'compliant', type: 'boolean', required: true, description: 'Whether the enterprise is tax compliant' },
      { name: 'lastFilingDate', type: 'string', required: true, description: 'Date of last tax filing' },
      { name: 'nextFilingDate', type: 'string', required: false, description: 'Date of next tax filing' },
      { name: 'taxYear', type: 'string', required: false, description: 'Tax year' },
    ],
    requiredClaims: ['taxId', 'compliant', 'lastFilingDate'],
    optionalClaims: ['nextFilingDate', 'taxYear'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    templateId: 'LicenseCredential',
    name: 'License Credential',
    description: 'Verifies that the enterprise has the necessary licenses',
    type: 'LicenseCredential',
    schemaId: 'https://stockexchange.io/schemas/license/v1',
    format: 'jsonld',
    claims: [
      { name: 'licenseNumber', type: 'string', required: true, description: 'License number' },
      { name: 'licenseType', type: 'string', required: true, description: 'Type of license' },
      { name: 'issuedAt', type: 'string', required: true, description: 'Date when issued' },
      { name: 'expiresAt', type: 'string', required: true, description: 'Date when expires' },
      { name: 'issuingAuthority', type: 'string', required: false, description: 'Issuing authority' },
      { name: 'status', type: 'string', required: false, description: 'License status', validation: { enum: ['active', 'expired', 'suspended'] } },
    ],
    requiredClaims: ['licenseNumber', 'licenseType', 'issuedAt', 'expiresAt'],
    optionalClaims: ['issuingAuthority', 'status'],
    defaultExpirationDays: 365,
    supportedChains: ['1', '5', '10', '56', '137'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];