/**
 * FJN 模块统一导出
 *
 * 福建老酒 369 全球生态系统 - 工业级实现
 * 遵循 H6 (领域模型) / H7 (数据库设计) / H14-H16 (后端规范)
 *
 * 模块组成：
 *  - constants  业务编号前缀、枚举常量、税率
 *  - decimal    Decimal 工具（与 H14 libs/decimal 一致）
 *  - errors     业务异常类层级
 *  - types      通用类型 + 状态机
 *  - services   业务 Service 实现（按 H15 顺序）
 *
 * 用法：
 *   import {
 *     FJN_PRODUCT_TYPES,
 *     FJN_ORDER_STATUS,
 *     FjnError,
 *     FjnValidationError,
 *     FjnBusinessNo,
 *     decimal,
 *   } from '@/lib/fjn';
 *
 *   // 创建商品
 *   import { FjnProductService } from '@/lib/fjn/services/product-service';
 *   const product = await FjnProductService.create({ ... });
 */

// 常量
export {
  // 业务编号前缀
  FJN_BUSINESS_NO_PREFIX,
  // 商品类型
  FJN_PRODUCT_TYPES,
  // 商品状态
  FJN_PRODUCT_STATUS,
  // 订单状态机
  FJN_ORDER_STATUS,
  FJN_ORDER_STATUS_FLOW,
  // 支付状态
  FJN_PAYMENT_STATUS,
  // 退款状态
  FJN_REFUND_STATUS,
  // 资产类型
  FJN_ASSET_TYPES,
  // 分账池类型
  FJN_POOL_TYPES,
  // 分账规则默认比例
  FJN_DEFAULT_REVENUE_RATIOS,
  // 推荐/团队/节点奖励默认比例
  FJN_DEFAULT_REWARD_RATIOS,
  // 风控事件类型
  FJN_RISK_EVENT_TYPES,
  // 审批状态
  FJN_APPROVAL_STATUS,
  // 节点等级
  FJN_NODE_LEVELS,
  // 团队层级
  FJN_TEAM_LEVELS,
  // 国家代码
  FJN_DEFAULT_COUNTRY,
  FJN_ALLOWED_COUNTRIES,
  // 货币
  FJN_DEFAULT_CURRENCY,
  FJN_SUPPORTED_CURRENCIES,
  // KYC 等级
  FJN_KYC_LEVELS,
} from './constants';

// Decimal
export {
  FjnDecimal,
  decimalAdd,
  decimalSub,
  decimalMul,
  decimalDiv,
  decimalMin,
  decimalMax,
  decimalEq,
  decimalGt,
  decimalGte,
  decimalLt,
  decimalLte,
  decimalToFixed,
  decimalToString,
  decimalToNumber,
  decimalIsZero,
  decimalIsPositive,
  decimalIsNegative,
  decimalFromPercent,
  decimalToPercent,
  decimalSum,
  decimalZero,
  decimalHundred,
  // 业务计算函数（H6 / H14）
  calculateWine369Revenue,
  calculateReferralReward,
  calculateTeamRewards,
  calculateNodeRewards,
  calculateTPointsConversion,
  type Wine369RevenueResult,
} from './decimal';

// 错误
export {
  FjnError,
  FjnValidationError,
  FjnNotFoundError,
  FjnConflictError,
  FjnUnauthorizedError,
  FjnForbiddenError,
  FjnBusinessRuleError,
  FjnStateMachineError,
  FjnExternalServiceError,
  FjnRateLimitError,
  FjnKycRequiredError,
  FjnRegionRestrictedError,
  FjnInsufficientBalanceError,
  FjnApprovalRequiredError,
} from './errors';

// 类型 + 业务编号
export {
  // 业务编号生成器
  FjnBusinessNoGenerator,
  // 状态机
  createStateMachine,
  // 工具类型
  type FjnResult,
  type FjnPaginatedResult,
  type FjnPaginationInput,
  type FjnListQuery,
  type FjnAuditedFields,
  type FjnSoftDeletable,
} from './types';

// Services - 工业级 23 Service 实现
// ✅ Product Service: 完整实现（含 CRUD、状态机、库存）—— 4 文件化导出见文末
// ✅ Order Service:   完整实现（含状态机、库存锁定、履约任务、退款）
// 🚧 Payment / Points / Revenue / NFT / Power / Release / Node / Team / Referral: 后续阶段
// 📋 其余 12 个: 后续阶段
export {
  FjnOrderService,
  createFjnOrderService,
  type CreateOrderInput,
  type ListOrderInput,
  type CancelOrderInput,
  type MarkOrderPaidInput,
  type RiskHoldOrderInput,
  type ConfirmOrderInput,
  type StartFulfillingInput,
  type FulfillmentDoneInput,
  type CompleteOrderInput,
  type MarkRefundedInput,
  /** Order Service 的退款申请入参（避免与 Payment Service 同名类型冲突） */
  type RequestRefundInput as RequestOrderRefundInput,
} from './services/order-service';

// Order Service 状态机 + 事件 + 错误
export {
  // 状态常量
  ORDER_STATUS,
  ORDER_PAYMENT_STATUS,
  ORDER_REFUND_STATUS,
  ORDER_RISK_STATUS,
  ORDER_TYPES,
  // 状态流转
  ORDER_STATUS_TRANSITIONS,
  ALL_ORDER_STATUSES,
  TERMINAL_ORDER_STATUSES,
  // 工具函数
  canTransitOrderStatus,
  assertTransitOrderStatus,
  nextOrderStatuses,
  isTerminalOrderStatus,
  isCancellable,
  isPayable,
  isFulfilling,
  // 类型
  type FjnOrderStatus,
  type FjnOrderPaymentStatus,
  type FjnOrderRefundStatus,
  type FjnOrderRiskStatus,
  type FjnOrderType,
} from './services/order-state-machine';

export {
  ORDER_EVENTS,
  ORDER_EVENT_SOURCES,
  type FjnOrderEvent,
  type FjnOrderEventSource,
  type OrderCreatedPayload,
  type OrderPaidPayload,
  type OrderCancelledPayload,
  type OrderConfirmedPayload,
  type OrderRiskHeldPayload,
  type OrderFulfilledPayload,
  type OrderRefundedPayload,
  type OrderEventPayload,
} from './services/order-events';

export {
  ORDER_ERROR_CODES,
  FjnOrderError,
  FjnOrderNotFoundError,
  FjnOrderStatusInvalidError,
  FjnProductNotActiveError,
  FjnStockInsufficientError,
  FjnOrderAmountInvalidError,
  FjnOrderRegionBlockedError,
  type FjnOrderErrorCode,
} from './services/order-errors';

// Services - 工业级 23 Service 实现
// ✅ Product Service:   完整实现（含 CRUD、状态机、库存）
// ✅ Order Service:     完整实现（含状态机、库存锁定、履约任务、退款）
// ✅ Payment Service:   完整实现（含状态机、tx_hash 唯一、回调幂等、与 OrderService 联动）
// 🚧 Revenue / Points / NFT / Power / Release / Node / Team / Referral: 后续阶段
// 📋 其余 12 个: 后续阶段
export { FjnPaymentService, createFjnPaymentService } from './services/payment-service';
export {
  type CreatePaymentInput,
  type ListPaymentInput,
  type MarkPaymentProcessingInput,
  type MarkPaymentSuccessInput,
  type MarkPaymentFailedInput,
  type HandleCallbackInput,
  type RequestRefundInput,
  type ApproveRefundInput,
  type RejectRefundInput,
  type MarkRefundProcessingInput,
  type MarkRefundSucceededInput,
  type MarkRefundFailedInput,
  type ListRefundInput,
} from './services/payment-service';

// Payment Service 状态机 + 事件 + 错误
export {
  // 支付单状态
  PAYMENT_STATUS,
  PAYMENT_STATUS_TRANSITIONS,
  ALL_PAYMENT_STATUSES,
  TERMINAL_PAYMENT_STATUSES,
  // 退款单状态
  REFUND_STATUS,
  REFUND_STATUS_TRANSITIONS,
  ALL_REFUND_STATUSES,
  TERMINAL_REFUND_STATUSES,
  // 支付方式
  PAYMENT_METHODS,
  CHAIN_TYPES,
  PAYMENT_PROVIDERS,
  REFUND_TYPES,
  REFUND_ADJUSTMENT_TYPES,
  // 工具函数
  isTerminalPaymentStatus,
  isTerminalRefundStatus,
  canTransitPaymentStatus,
  assertTransitPaymentStatus,
  nextPaymentStatuses,
  canTransitRefundStatus,
  assertTransitRefundStatus,
  nextRefundStatuses,
  isPayablePayment,
  isPaymentSucceeded,
  isRefundablePayment,
  // 类型
  type FjnPaymentStatus,
  type FjnRefundStatus,
  type FjnPaymentMethod,
  type FjnChainType,
  type FjnPaymentProvider,
  type FjnRefundType,
  type FjnRefundAdjustmentType,
} from './services/payment-state-machine';

export {
  PAYMENT_EVENTS,
  PAYMENT_EVENT_SOURCES,
  type FjnPaymentEvent,
  type FjnPaymentEventSource,
  type PaymentCreatedPayload,
  type PaymentSucceededPayload,
  type PaymentFailedPayload,
  type PaymentExpiredPayload,
  type RefundRequestedPayload,
  type RefundApprovedPayload,
  type RefundRejectedPayload,
  type RefundSucceededPayload,
  type PaymentEventPayload,
} from './services/payment-events';

export {
  PAYMENT_ERROR_CODES,
  FjnPaymentError,
  FjnPaymentNotFoundError,
  FjnPaymentStatusInvalidError,
  FjnPaymentAmountInvalidError,
  FjnPaymentAmountMismatchError,
  FjnPaymentCurrencyMismatchError,
  FjnPaymentTxHashDuplicatedError,
  FjnRefundNotFoundError,
  FjnRefundStatusInvalidError,
  FjnRefundAmountInvalidError,
  FjnPaymentCallbackSignatureInvalidError,
  FjnPaymentExpiredError,
  FjnOrderNotPayableError,
  type FjnPaymentErrorCode,
} from './services/payment-errors';

// Revenue Service 状态机 + 事件 + 错误
export {
  ALLOCATION_STATUS,
  ALLOCATION_STATUS_TRANSITIONS,
  ALL_ALLOCATION_STATUSES,
  TERMINAL_ALLOCATION_STATUSES,
  REVERSAL_STATUS,
  REVERSAL_STATUS_TRANSITIONS,
  ALL_REVERSAL_STATUSES,
  TERMINAL_REVERSAL_STATUSES,
  REVENUE_POOLS,
  WINE_369_REVENUE_RULE,
  canTransitAllocationStatus,
  canTransitReversalStatus,
  assertTransitAllocationStatus,
  assertTransitReversalStatus,
  isTerminalAllocationStatus,
  isTerminalReversalStatus,
  isApprovable,
  isReversible,
  isCancellableAllocation,
  isRiskCheckable,
  isAllocationSettled,
  nextAllocationStatuses,
  nextReversalStatuses,
  type FjnAllocationStatus,
  type FjnReversalStatus,
  type FjnRevenuePoolType,
} from './services/revenue-state-machine';

export {
  REVENUE_EVENTS,
  REVENUE_EVENT_SOURCES,
  ALL_REVENUE_EVENTS,
  REVENUE_EVENT_COUNT,
  isValidRevenueEvent,
  isValidRevenueEventSource,
  extractDomain,
  extractAction,
  type FjnRevenueEvent,
  type FjnRevenueEventSource,
  type AllocationRequestedPayload,
  type AllocatedPayload,
  type ApprovedPayload,
  type SettledPayload,
  type ReversalRequestedPayload,
  type ReversedPayload,
  type RiskCheckPassedPayload,
  type RiskCheckFailedPayload,
  type RevenueEventPayload,
} from './services/revenue-events';

export {
  REVENUE_ERROR_CODES,
  FjnRevenueError,
  FjnAllocationNotFoundError,
  FjnAllocationAlreadyExistsError,
  FjnAllocationStatusInvalidError,
  FjnAllocationTerminalStatusError,
  FjnAllocationNotReversibleError,
  FjnAllocationNotApprovableError,
  FjnAllocationAmountInvalidError,
  FjnAllocationAmountZeroError,
  FjnReversalNotFoundError,
  FjnReversalAlreadyExistsError,
  FjnReversalStatusInvalidError,
  FjnReversalAmountInvalidError,
  FjnReversalAmountExceedsError,
  FjnRevenueOrderNotFoundError,
  FjnRevenueOrderNotPaidError,
  FjnRuleNotFoundError,
  FjnRuleInvalidError,
  FjnRuleInactiveError,
  FjnReviewerRequiredError,
  isFjnRevenueErrorCode,
  getRevenueErrorCodeCount,
  type FjnRevenueErrorCode,
} from './services/revenue-errors';

export { FjnRevenueService, createFjnRevenueService } from './services/revenue-service';
export {
  type CreateAllocationInput,
  type ListAllocationInput,
  type ApproveAllocationInput,
  type CancelAllocationInput,
  type CreateReversalInput,
  type ListReversalInput,
  type PoolSummaryInput,
} from './services/revenue-service';

// Team Service 状态机 + 事件 + 错误
export {
  TEAM_REWARD_STATUS,
  TEAM_REWARD_STATUS_TRANSITIONS,
  ALL_TEAM_REWARD_STATUSES,
  TERMINAL_TEAM_REWARD_STATUSES,
  TEAM_STRUCTURE_STATUS,
  TEAM_STRUCTURE_STATUS_TRANSITIONS,
  ALL_TEAM_STRUCTURE_STATUSES,
  TEAM_SERVICE_RECORD_STATUS,
  TEAM_SERVICE_RECORD_STATUS_TRANSITIONS,
  ALL_TEAM_SERVICE_RECORD_STATUSES,
  TERMINAL_TEAM_SERVICE_RECORD_STATUSES,
  TEAM_REWARD_RATES,
  TEAM_LEVEL_RATES,
  TEAM_LEVEL_FIELD,
  TEAM_SERVICE_TYPES,
  canTransitTeamRewardStatus,
  canTransitTeamStructureStatus,
  canTransitTeamServiceRecordStatus,
  assertTransitTeamRewardStatus,
  assertTransitTeamStructureStatus,
  assertTransitTeamServiceRecordStatus,
  isTerminalTeamRewardStatus,
  isWaitingServiceRecord,
  isLockable,
  isApprovableReward,
  isPayableReward,
  isPayableNow,
  isRecoverable,
  isCancellableReward,
  isServiceRecordApprovable,
  nextTeamRewardStatuses,
  nextTeamStructureStatuses,
  nextTeamServiceRecordStatuses,
  type FjnTeamRewardStatus,
  type FjnTeamStructureStatus,
  type FjnTeamServiceRecordStatus,
  type FjnTeamLevel,
  type FjnTeamServiceType,
} from './services/team-state-machine';

export {
  TEAM_EVENTS,
  TEAM_EVENT_SOURCES,
  ALL_TEAM_EVENTS,
  TEAM_EVENT_COUNT,
  isValidTeamEvent,
  isValidTeamEventSource,
  type FjnTeamEvent,
  type FjnTeamEventSource,
  type StructureCreatedPayload,
  type StructureUpdatedPayload,
  type ServiceRecordCreatedPayload,
  type ServiceRecordApprovedPayload,
  type ServiceRecordRejectedPayload,
  type TeamRewardCreatedPayload,
  type TeamRewardWaitingServicePayload,
  type TeamRewardLockedPayload,
  type TeamRewardApprovedPayload,
  type TeamRewardPayablePayload,
  type TeamRewardPaidPayload,
  type TeamRewardRecoveredPayload,
  type TeamRewardCancelledPayload,
  type TeamRewardRiskHoldPayload,
  type TeamEventPayload,
} from './services/team-events';

export {
  TEAM_ERROR_CODES,
  FjnTeamError,
  FjnTeamStructureNotFoundError,
  FjnTeamStructureAlreadyExistsError,
  FjnTeamStructureInvalidError,
  FjnTeamStructureLoopNotAllowedError,
  FjnTeamStructureSuspendedError,
  FjnTeamStructureInactiveError,
  FjnTeamServiceRecordNotFoundError,
  FjnTeamServiceRecordInvalidError,
  FjnTeamServiceRecordTypeInvalidError,
  FjnTeamServiceRecordDurationInvalidError,
  FjnTeamRewardNotFoundError,
  FjnTeamRewardAlreadyExistsError,
  FjnTeamRewardStatusInvalidError,
  FjnTeamRewardTerminalStatusError,
  FjnTeamRewardAmountInvalidError,
  FjnTeamRewardAmountZeroError,
  FjnTeamRewardRateInvalidError,
  FjnTeamRewardLevelInvalidError,
  FjnTeamRewardNotLockableError,
  FjnTeamRewardNotApprovableError,
  FjnTeamRewardNotPayableError,
  FjnTeamRewardNotRecoverableError,
  FjnTeamRewardNotCancellableError,
  FjnTeamRewardServiceRecordRequiredError,
  FjnTeamRewardServiceRecordNotApprovedError,
  FjnTeamRewardNoUplineError,
  FjnTeamOrderNotFoundError,
  FjnTeamOrderNotPaidError,
  FjnTeamKycNotVerifiedError,
  FjnTeamRiskHoldError,
  FjnTeamApprovalRequiredError,
  FjnTeamReviewerRequiredError,
  FjnTeamReasonRequiredError,
  isFjnTeamErrorCode,
  getTeamErrorCodeCount,
  type FjnTeamErrorCode,
} from './services/team-errors';

export { FjnTeamService, createFjnTeamService } from './services/team-service';
export {
  type CreateTeamRewardInput,
  type ApproveTeamRewardInput,
  type RecoverTeamRewardInput,
  type CancelTeamRewardInput,
  type ListTeamRewardInput,
  type CreateStructureInput,
  type ListStructureInput,
  type SubmitServiceRecordInput,
  type ReviewServiceRecordInput,
  type ListServiceRecordInput,
} from './services/team-service';

// Node Service 状态机 + 事件 + 错误
export {
  NODE_STATUS,
  NODE_STATUS_TRANSITIONS,
  ALL_NODE_STATUSES,
  TERMINAL_NODE_STATUSES,
  NODE_KYB_STATUS,
  NODE_KYB_STATUS_TRANSITIONS,
  ALL_NODE_KYB_STATUSES,
  TERMINAL_NODE_KYB_STATUSES,
  NODE_REWARD_STATUS,
  NODE_REWARD_STATUS_TRANSITIONS,
  ALL_NODE_REWARD_STATUSES,
  TERMINAL_NODE_REWARD_STATUSES,
  NODE_SERVICE_RECORD_STATUS,
  NODE_SERVICE_RECORD_STATUS_TRANSITIONS,
  ALL_NODE_SERVICE_RECORD_STATUSES,
  TERMINAL_NODE_SERVICE_RECORD_STATUSES,
  NODE_LEVELS,
  ALL_NODE_LEVELS,
  NODE_LEVEL_RANK,
  NODE_REWARD_RATES,
  NODE_LEVEL_RATES,
  NODE_REWARD_LEVELS,
  NODE_SERVICE_TYPES,
  canTransitNodeStatus,
  canTransitNodeKybStatus,
  canTransitNodeRewardStatus,
  canTransitNodeServiceRecordStatus,
  assertTransitNodeStatus,
  assertTransitNodeKybStatus,
  assertTransitNodeRewardStatus,
  assertTransitNodeServiceRecordStatus,
  isTerminalNodeStatus,
  isTerminalNodeRewardStatus,
  isTerminalNodeKybStatus,
  isTerminalNodeServiceRecordStatus,
  isNodeRewardLockable,
  isNodeRewardApprovable,
  isNodeRewardPayableReward,
  isNodeRewardPayableNow,
  isNodeRewardRecoverable,
  isNodeRewardCancellable,
  isNodeRewardEligible,
  isNodeServiceRecordApprovable,
  isNodeRewardLevel,
  nextNodeStatuses,
  nextNodeKybStatuses,
  nextNodeRewardStatuses,
  nextNodeServiceRecordStatuses,
  type FjnNodeStatus,
  type FjnNodeKybStatus,
  type FjnNodeRewardStatus,
  type FjnNodeServiceRecordStatus,
  type FjnNodeLevel,
  type FjnNodeRewardLevel,
  type FjnNodeServiceType,
} from './services/node-state-machine';

export {
  NODE_EVENTS,
  NODE_EVENT_SOURCES,
  ALL_NODE_EVENTS,
  NODE_EVENT_COUNT,
  isValidNodeEvent,
  isValidNodeEventSource,
  type FjnNodeEvent,
  type FjnNodeEventSource,
  type NodeCreatedPayload,
  type NodeApprovedPayload,
  type NodeActivatedPayload,
  type NodeRestrictedPayload,
  type NodeSuspendedPayload,
  type NodeTerminatedPayload,
  type NodeBlacklistedPayload,
  type KybSubmittedPayload,
  type KybApprovedPayload,
  type KybRejectedPayload,
  type NodeServiceRecordCreatedPayload,
  type NodeServiceRecordApprovedPayload,
  type NodeServiceRecordRejectedPayload,
  type NodeRewardCreatedPayload,
  type NodeRewardWaitingServicePayload,
  type NodeRewardLockedPayload,
  type NodeRewardApprovedPayload,
  type NodeRewardPayablePayload,
  type NodeRewardPaidPayload,
  type NodeRewardRecoveredPayload,
  type NodeRewardCancelledPayload,
  type NodeRewardRiskHoldPayload,
  type NodeEventPayload,
} from './services/node-events';

export {
  NODE_ERROR_CODES,
  FjnNodeError,
  FjnNodeNotFoundError,
  FjnNodeAlreadyExistsError,
  FjnNodeInvalidError,
  FjnNodeLevelInvalidError,
  FjnNodeRegionInvalidError,
  FjnNodeNotActiveError,
  FjnNodeNotApprovedError,
  FjnNodeSuspendedError,
  FjnNodeTerminatedError,
  FjnNodeBlacklistedError,
  FjnNodeRestrictedError,
  FjnNodeNotRewardEligibleError,
  FjnNodeAlreadyTerminatedError,
  FjnNodeAlreadyBlacklistedError,
  FjnNodeKybNotSubmittedError,
  FjnNodeKybAlreadyApprovedError,
  FjnNodeKybAlreadyRejectedError,
  FjnNodeKybInvalidStatusError,
  FjnNodeKybRequiredError,
  FjnNodeKybAgreementRequiredError,
  FjnNodeServiceRecordNotFoundError,
  FjnNodeServiceRecordInvalidError,
  FjnNodeServiceRecordTypeInvalidError,
  FjnNodeServiceRecordParticipantsInvalidError,
  FjnNodeRewardNotFoundError,
  FjnNodeRewardAlreadyExistsError,
  FjnNodeRewardStatusInvalidError,
  FjnNodeRewardTerminalStatusError,
  FjnNodeRewardAmountInvalidError,
  FjnNodeRewardAmountZeroError,
  FjnNodeRewardRateInvalidError,
  FjnNodeRewardLevelInvalidError,
  FjnNodeRewardStrategicNotEligibleError,
  FjnNodeRewardNotLockableError,
  FjnNodeRewardNotApprovableError,
  FjnNodeRewardNotPayableError,
  FjnNodeRewardNotRecoverableError,
  FjnNodeRewardNotCancellableError,
  FjnNodeRewardServiceRecordRequiredError,
  FjnNodeRewardServiceRecordNotApprovedError,
  FjnNodeRewardNoNodeError,
  FjnNodeOrderNotFoundError,
  FjnNodeOrderNotPaidError,
  FjnNodeKycNotVerifiedError,
  FjnNodeRiskHoldError,
  FjnNodeApproverRequiredError,
  FjnNodeReviewerRequiredError,
  FjnNodeReasonRequiredError,
  isFjnNodeErrorCode,
  getNodeErrorCodeCount,
  type FjnNodeErrorCode,
} from './services/node-errors';

export { FjnNodeService, createFjnNodeService } from './services/node-service';
export {
  type CreateNodeInput,
  type ApproveNodeInput,
  type SuspendNodeInput,
  type ListNodeInput,
  type CreateNodeRewardInput,
  type ApproveNodeRewardInput,
  type RecoverNodeRewardInput,
  type CancelNodeRewardInput,
  type ListNodeRewardInput,
  type SubmitNodeServiceRecordInput,
  type ReviewNodeServiceRecordInput,
  type ListNodeServiceRecordInput,
} from './services/node-service';

// Finance Service 状态机 + 事件 + 错误（H032）
export {
  FINANCE_ACCOUNT_STATUS,
  FINANCE_ACCOUNT_STATUS_TRANSITIONS,
  ALL_FINANCE_ACCOUNT_STATUSES,
  TERMINAL_FINANCE_ACCOUNT_STATUSES,
  FINANCE_LEDGER_STATUS,
  FINANCE_LEDGER_STATUS_TRANSITIONS,
  ALL_FINANCE_LEDGER_STATUSES,
  TERMINAL_FINANCE_LEDGER_STATUSES,
  FINANCE_DIRECTION,
  FINANCE_SETTLEMENT_STATUS,
  FINANCE_SETTLEMENT_STATUS_TRANSITIONS,
  ALL_FINANCE_SETTLEMENT_STATUSES,
  TERMINAL_FINANCE_SETTLEMENT_STATUSES,
  FINANCE_SETTLEMENT_ITEM_STATUS,
  FINANCE_SETTLEMENT_ITEM_STATUS_TRANSITIONS,
  ALL_FINANCE_SETTLEMENT_ITEM_STATUSES,
  TERMINAL_FINANCE_SETTLEMENT_ITEM_STATUSES,
  FINANCE_ACCOUNT_TYPES,
  ALL_FINANCE_ACCOUNT_TYPES,
  FINANCE_BUSINESS_TYPES,
  ALL_FINANCE_BUSINESS_TYPES,
  FINANCE_SETTLEMENT_TYPES,
  ALL_FINANCE_SETTLEMENT_TYPES,
  canTransitFinanceAccountStatus,
  canTransitFinanceLedgerStatus,
  canTransitFinanceSettlementStatus,
  canTransitFinanceSettlementItemStatus,
  assertTransitFinanceAccountStatus,
  assertTransitFinanceLedgerStatus,
  assertTransitFinanceSettlementStatus,
  assertTransitFinanceSettlementItemStatus,
  isTerminalFinanceAccountStatus,
  isTerminalFinanceLedgerStatus,
  isTerminalFinanceSettlementStatus,
  isTerminalFinanceSettlementItemStatus,
  isFinanceAccountOperable,
  isFinanceLedgerReversible,
  isFinanceSettlementApprovable,
  isFinanceSettlementPayable,
  isFinanceSettlementCancellable,
  isFinanceSettlementItemPayable,
  isFinanceSettlementItemRetriable,
  nextFinanceAccountStatuses,
  nextFinanceLedgerStatuses,
  nextFinanceSettlementStatuses,
  nextFinanceSettlementItemStatuses,
  type FjnFinanceAccountStatus,
  type FjnFinanceLedgerStatus,
  type FjnFinanceDirection,
  type FjnFinanceSettlementStatus,
  type FjnFinanceSettlementItemStatus,
  type FjnFinanceAccountType,
  type FjnFinanceBusinessType,
  type FjnFinanceSettlementType,
} from './services/finance-state-machine';

export {
  FINANCE_EVENTS,
  FINANCE_EVENT_SOURCES,
  ALL_FINANCE_EVENTS,
  FINANCE_EVENT_COUNT,
  isValidFinanceEvent,
  isValidFinanceEventSource,
  type FjnFinanceEvent,
  type FjnFinanceEventSource,
  type AccountCreatedPayload,
  type AccountFrozenPayload,
  type AccountUnfrozenPayload,
  type AccountClosedPayload,
  type LedgerPostedPayload,
  type LedgerReversedPayload,
  type LedgerVoidedPayload,
  type RevenueRecognizedPayload,
  type Revenue369AllocatedPayload,
  type SettlementCreatedPayload,
  type SettlementApprovedPayload,
  type SettlementPaidPayload,
  type SettlementCancelledPayload,
  type SettlementItemPaidPayload,
  type SettlementItemFailedPayload,
  type FinanceEventPayload,
} from './services/finance-events';

export {
  FINANCE_ERROR_CODES,
  ALL_FINANCE_ERROR_CODES,
  FINANCE_ERROR_CODE_COUNT,
  isFjnFinanceErrorCode,
  getFinanceErrorCodeCount,
  isFjnFinanceError,
  FjnFinanceAccountNotFoundError,
  FjnFinanceAccountAlreadyExistsError,
  FjnFinanceAccountFrozenError,
  FjnFinanceAccountClosedError,
  FjnFinanceAccountStatusInvalidError,
  FjnFinanceAccountTypeInvalidError,
  FjnFinanceAccountBalanceNegativeError,
  FjnFinanceLedgerNotFoundError,
  FjnFinanceLedgerAlreadyReversedError,
  FjnFinanceLedgerAlreadyVoidedError,
  FjnFinanceLedgerAmountInvalidError,
  FjnFinanceLedgerAmountNegativeError,
  FjnFinanceLedgerAmountZeroError,
  FjnFinanceLedgerDirectionInvalidError,
  FjnFinanceLedgerBalanceMismatchError,
  FjnFinanceLedgerCurrencyMismatchError,
  FjnFinanceLedgerSourceInvalidError,
  FjnFinanceLedgerReverseNotAllowedError,
  FjnFinanceSettlementNotFoundError,
  FjnFinanceSettlementAlreadyExistsError,
  FjnFinanceSettlementStatusInvalidError,
  FjnFinanceSettlementNotApprovableError,
  FjnFinanceSettlementNotPayableError,
  FjnFinanceSettlementNotCancellableError,
  FjnFinanceSettlementAmountInvalidError,
  FjnFinanceSettlementPeriodInvalidError,
  FjnFinanceSettlementNoItemsError,
  FjnFinanceSettlementAlreadyPaidError,
  FjnFinanceSettlementItemNotFoundError,
  FjnFinanceSettlementItemNotPayableError,
  FjnFinanceSettlementItemNotRetriableError,
  FjnFinanceSettlementItemBankInfoRequiredError,
  FjnFinanceSettlementItemAmountInvalidError,
  FjnFinanceAmountInvalidError,
  FjnFinanceCurrencyMismatchError,
  FjnFinanceCurrencyNotSupportedError,
  FjnFinanceApproverRequiredError,
  FjnFinanceOperatorRequiredError,
  FjnFinanceReasonRequiredError,
  FjnFinancePeriodLockedError,
  FjnFinanceDailyLimitExceededError,
  FjnFinanceRevenue369AmountMismatchError,
  FjnFinanceRevenue369OrderRequiredError,
  FjnFinanceRevenue369RuleVersionInvalidError,
  FjnFinanceRevenue369PoolsNotInitializedError,
  FjnFinanceReportPeriodInvalidError,
  FjnFinanceReportNotFoundError,
  type FjnFinanceErrorCode,
} from './services/finance-errors';

export { FjnFinanceService, createFjnFinanceService } from './services/finance-service';
export {
  type CreateAccountInput,
  type PostLedgerInput,
  type ReverseLedgerInput,
  type RecognizeWine369Input,
  type CreateSettlementInput,
  type AddSettlementItemInput,
  type ApproveSettlementInput,
  type PaySettlementItemInput,
  type CancelSettlementInput,
  type FreezeAccountInput,
  type UnfreezeAccountInput,
  type CloseAccountInput,
} from './services/finance-service';

// =====================================================================
// Tax Service 状态机 + 事件 + 错误 + 主体
// =====================================================================
export {
  // 状态常量
  TAX_RULE_STATUS,
  TAX_RECORD_STATUS,
  TAX_REPORT_STATUS,
  TAX_TYPES,
  TAX_MODE,
  ALL_TAX_RULE_STATUSES,
  ALL_TAX_RECORD_STATUSES,
  ALL_TAX_REPORT_STATUSES,
  TERMINAL_TAX_RULE_STATUSES,
  TERMINAL_TAX_RECORD_STATUSES,
  TERMINAL_TAX_REPORT_STATUSES,
  ALL_TAX_TYPES,
  // 状态流转
  TAX_RULE_STATUS_TRANSITIONS,
  TAX_RECORD_STATUS_TRANSITIONS,
  TAX_REPORT_STATUS_TRANSITIONS,
  // 工具函数
  isTerminalTaxRuleStatus,
  isTerminalTaxRecordStatus,
  isTerminalTaxReportStatus,
  canTransitTaxRuleStatus,
  canTransitTaxRecordStatus,
  canTransitTaxReportStatus,
  assertTransitTaxRuleStatus,
  assertTransitTaxRecordStatus,
  assertTransitTaxReportStatus,
  nextTaxRuleStatuses,
  nextTaxRecordStatuses,
  nextTaxReportStatuses,
  isTaxRuleUsable,
  isTaxRecordPayable,
  isTaxReportSubmittable,
  // 类型
  type FjnTaxRuleStatus,
  type FjnTaxRecordStatus,
  type FjnTaxReportStatus,
  type FjnTaxType,
  type FjnTaxMode,
} from './services/tax-state-machine';

export {
  TAX_EVENTS,
  TAX_EVENT_SOURCES,
  ALL_TAX_EVENTS,
  TAX_EVENT_COUNT,
  isValidTaxEvent,
  isValidTaxEventSource,
  type FjnTaxEvent,
  type FjnTaxEventSource,
  type TaxRuleCreatedPayload,
  type TaxRuleUpdatedPayload,
  type TaxRuleArchivedPayload,
  type TaxCalculatedPayload,
  type TaxRecordedPayload,
  type TaxPaidPayload,
  type TaxAdjustedPayload,
  type TaxReversedPayload,
  type TaxReportCreatedPayload,
  type TaxReportSubmittedPayload,
  type TaxReportPaidPayload,
  type TaxReportRejectedPayload,
  type TaxEventPayload,
} from './services/tax-events';

export {
  TAX_ERROR_CODES,
  ALL_TAX_ERROR_CODES,
  TAX_ERROR_CODE_COUNT,
  isFjnTaxErrorCode,
  getTaxErrorCodeCount,
  isFjnTaxError,
  FjnTaxRuleNotFoundError,
  FjnTaxRuleAlreadyExistsError,
  FjnTaxRuleNotActiveError,
  FjnTaxRuleInvalidRateError,
  FjnTaxRuleEffectiveInvalidError,
  FjnTaxRuleArchivedError,
  FjnTaxRecordNotFoundError,
  FjnTaxRecordAlreadyExistsError,
  FjnTaxRecordStatusInvalidError,
  FjnTaxRecordNotPayableError,
  FjnTaxRecordNotAdjustableError,
  FjnTaxRecordNotReversibleError,
  FjnTaxRecordTaxableInvalidError,
  FjnTaxRecordTaxAmountInvalidError,
  FjnTaxRecordTaxRateMismatchError,
  FjnTaxAmountInvalidError,
  FjnTaxCurrencyMismatchError,
  FjnTaxRateInvalidError,
  FjnTaxModeInvalidError,
  FjnTaxReportNotFoundError,
  FjnTaxReportAlreadyExistsError,
  FjnTaxReportStatusInvalidError,
  FjnTaxReportNotSubmittableError,
  FjnTaxReportNotPayableError,
  FjnTaxReportPeriodInvalidError,
  FjnTaxReportNoRecordsError,
  FjnTaxReportSubmissionFailedError,
  FjnTaxCountryNotSupportedError,
  FjnTaxRegionNotSupportedError,
  FjnTaxRuleCodeRequiredError,
  FjnTaxTypeRequiredError,
  FjnTaxCurrencyRequiredError,
  FjnTaxReasonRequiredError,
  FjnTaxApproverRequiredError,
  type FjnTaxErrorCode,
} from './services/tax-errors';

export { FjnTaxService, createFjnTaxService } from './services/tax-service';
export {
  type CreateTaxRuleInput,
  type UpdateTaxRuleInput,
  type ArchiveTaxRuleInput,
  type CalculateTaxInput,
  type RecordTaxInput,
  type MarkTaxPaidInput,
  type AdjustTaxInput,
  type ReverseTaxInput,
  type CreateTaxReportInput,
  type SubmitTaxReportInput,
  type MarkReportPaidInput,
  type RejectReportInput,
  type TaxCalculationResult,
} from './services/tax-service';

// =====================================================================
// Risk Service 状态机 + 事件 + 错误 + 主体
// =====================================================================
export {
  // 状态常量
  RISK_EVENT_STATUS,
  RISK_CASE_STATUS,
  RISK_LEVEL,
  RISK_ACTION,
  RISK_TYPE,
  RISK_SCORE_TYPE,
  BLACKLIST_CATEGORY,
  BLACKLIST_SOURCE as RISK_BLACKLIST_SOURCE,
  ALL_RISK_EVENT_STATUSES,
  ALL_RISK_CASE_STATUSES,
  ALL_RISK_LEVELS,
  ALL_RISK_ACTIONS,
  ALL_RISK_TYPES,
  ALL_RISK_SCORE_TYPES,
  ALL_BLACKLIST_CATEGORIES,
  TERMINAL_RISK_EVENT_STATUSES,
  TERMINAL_RISK_CASE_STATUSES,
  RISK_LEVEL_SCORE,
  // 状态流转
  RISK_EVENT_STATUS_TRANSITIONS,
  RISK_CASE_STATUS_TRANSITIONS,
  // 工具函数
  isTerminalRiskEventStatus,
  isTerminalRiskCaseStatus,
  canTransitRiskEventStatus,
  canTransitRiskCaseStatus,
  assertTransitRiskEventStatus,
  assertTransitRiskCaseStatus,
  nextRiskEventStatuses,
  nextRiskCaseStatuses,
  isRiskEventReviewable,
  isRiskEventResolvable,
  isRiskEventEscalable,
  isRiskCaseAssignable,
  isRiskCaseResolvable,
  deriveRiskLevelFromScore,
  // 类型
  type FjnRiskEventStatus,
  type FjnRiskCaseStatus,
  type FjnRiskLevel,
  type FjnRiskAction,
  type FjnRiskType,
  type FjnRiskScoreType,
  type FjnBlacklistCategory,
  type FjnBlacklistSource as FjnRiskBlacklistSource,
} from './services/risk-state-machine';

export {
  RISK_EVENTS,
  RISK_EVENT_SOURCES,
  ALL_RISK_EVENTS,
  RISK_EVENT_COUNT,
  isValidRiskEvent,
  isValidRiskEventSource,
  type FjnRiskEvent,
  type FjnRiskEventSource,
  type RiskRuleCreatedPayload,
  type RiskRuleUpdatedPayload,
  type RiskRuleDisabledPayload,
  type RiskRuleEnabledPayload,
  type RiskEventRecordedPayload,
  type RiskEventReviewingPayload,
  type RiskEventResolvedPayload,
  type RiskEventEscalatedPayload,
  type RiskCaseOpenedPayload,
  type RiskCaseAssignedPayload,
  type RiskCaseResolvedPayload,
  type RiskCaseClosedPayload,
  type RiskCaseReopenedPayload,
  type RiskScoreUpdatedPayload,
  type BlacklistAddedPayload,
  type BlacklistRemovedPayload,
  type BlacklistExpiredPayload,
  type DeviceRegisteredPayload,
  type DeviceUpdatedPayload,
  type RiskEventPayload,
} from './services/risk-events';

export {
  RISK_ERROR_CODES,
  ALL_RISK_ERROR_CODES,
  RISK_ERROR_CODE_COUNT,
  isFjnRiskErrorCode,
  getRiskErrorCodeCount,
  isFjnRiskError,
  FjnRiskRuleNotFoundError,
  FjnRiskRuleAlreadyExistsError,
  FjnRiskRuleNotActiveError,
  FjnRiskRuleInvalidConfigError,
  FjnRiskRuleInvalidLevelError,
  FjnRiskRuleInvalidActionError,
  FjnRiskRuleDisabledError,
  FjnRiskEventNotFoundError,
  FjnRiskEventAlreadyExistsError,
  FjnRiskEventStatusInvalidError,
  FjnRiskEventNotReviewableError,
  FjnRiskEventNotResolvableError,
  FjnRiskEventNotEscalableError,
  FjnRiskEventInvalidScoreError,
  FjnRiskCaseNotFoundError,
  FjnRiskCaseAlreadyExistsError,
  FjnRiskCaseStatusInvalidError,
  FjnRiskCaseNotAssignableError,
  FjnRiskCaseNotResolvableError,
  FjnRiskCaseNotClosableError,
  FjnRiskCaseNotReopenableError,
  FjnRiskCaseAssigneeRequiredError,
  FjnRiskScoreInvalidError,
  FjnRiskScoreNegativeError,
  FjnRiskScoreTypeInvalidError,
  FjnRiskScoreUserRequiredError,
  FjnRiskBlacklistNotFoundError,
  FjnRiskBlacklistAlreadyExistsError,
  FjnRiskBlacklistCategoryInvalidError,
  FjnRiskBlacklistValueRequiredError,
  FjnRiskBlacklistNotActiveError,
  FjnRiskBlacklistExpiredError,
  FjnRiskBlacklistTargetCheckFailedError,
  FjnRiskDeviceNotFoundError,
  FjnRiskDeviceAlreadyExistsError,
  FjnRiskDeviceFingerprintRequiredError,
  FjnRiskLevelInvalidError,
  FjnRiskActionInvalidError,
  FjnRiskTypeInvalidError,
  FjnRiskReasonRequiredError,
  FjnRiskReviewerRequiredError,
  FjnRiskResolutionRequiredError,
  FjnRiskOperatorRequiredError,
  FjnRiskEvaluationFailedError,
  type FjnRiskErrorCode,
} from './services/risk-errors';

export { FjnRiskService, createFjnRiskService } from './services/risk-service';
export {
  type CreateRiskRuleInput,
  type UpdateRiskRuleInput,
  type DisableRiskRuleInput,
  type EnableRiskRuleInput,
  type RecordRiskEventInput,
  type ReviewRiskEventInput,
  type ResolveRiskEventInput,
  type EscalateRiskEventInput,
  type OpenRiskCaseInput,
  type AssignRiskCaseInput,
  type ResolveRiskCaseInput,
  type CloseRiskCaseInput,
  type ReopenRiskCaseInput,
  type UpdateRiskScoreInput,
  type AddBlacklistInput as AddRiskBlacklistInput,
  type RemoveBlacklistInput,
  type RegisterDeviceInput,
} from './services/risk-service';

// ============================================================
// KYC Service (H018) - 阶段I 底座
// ============================================================
export {
  KYC_STATUS,
  KYC_LEVEL,
  KYC_DOCUMENT_TYPE,
  KYC_RISK_STATUS,
  KYC_PROVIDER,
  KYC_STATUS_TRANSITIONS,
  ALL_KYC_STATUSES,
  ALL_KYC_LEVELS,
  ALL_KYC_DOCUMENT_TYPES,
  ALL_KYC_RISK_STATUSES,
  ALL_KYC_PROVIDERS,
  TERMINAL_KYC_STATUSES,
  VALID_KYC_DB_STATUSES,
  isValidKycStatus,
  isValidKycDbStatus,
  isTerminalKycStatus,
  canTransitKycStatus,
  assertTransitKycStatus,
  nextKycStatuses,
  isKycReviewable,
  isKycApprovable,
  isKycRejectable,
  isKycManualReviewable,
  isKycResubmittable,
  isValidCountryCode,
  type FjnKycStatus,
  type FjnKycLevel,
  type FjnKycDocumentType,
  type FjnKycRiskStatus,
  type FjnKycProvider,
} from './services/kyc-state-machine';

export {
  KYC_EVENTS,
  KYC_EVENT_SOURCES,
  ALL_KYC_EVENTS,
  ALL_KYC_EVENT_SOURCES,
  type FjnKycEventName,
  type FjnKycEventSource,
  type KycSubmittedPayload,
  type KycApprovedPayload,
  type KycRejectedPayload,
  type KycExpiredPayload,
  type KycManualReviewPayload,
  type KycResubmittedPayload,
  type KycCompanySubmittedPayload,
  type KycCompanyApprovedPayload,
  type KycCompanyRejectedPayload,
  type KycCompanyExpiredPayload,
  type KycCompanyManualReviewPayload,
  type FjnKycEventPayloadMap,
} from './services/kyc-events';

export {
  KYC_ERROR_CODES,
  type FjnKycErrorCode,
  FjnKycError,
  FjnKycNotFoundError,
  FjnKycAlreadySubmittedError,
  FjnKycAlreadyApprovedError,
  FjnKycAlreadyRejectedError,
  FjnKycStatusInvalidError,
  FjnKycStatusNotApprovableError,
  FjnKycStatusNotRejectableError,
  FjnKycStatusNotManualReviewableError,
  FjnKycStatusNotResubmittableError,
  FjnKycDocumentRequiredError,
  FjnKycDocumentTypeInvalidError,
  FjnKycDocumentCountryInvalidError,
  FjnKycLevelInvalidError,
  FjnKycProviderInvalidError,
  FjnKycReviewerIdRequiredError,
  FjnKycReviewNoteRequiredError,
  FjnKybNotFoundError,
  FjnKybAlreadySubmittedError,
  FjnKybStatusInvalidError,
  FjnKybDocumentRequiredError,
  FjnKybCompanyNameRequiredError,
  FjnKybRegistrationCountryInvalidError,
  FjnKycExternalServiceError,
  FjnKycThirdPartyTimeoutError,
} from './services/kyc-errors';

export {
  FjnKycService,
  KYC_DEFAULT_EXPIRES_DAYS,
  KYC_REJECT_NOTE_MIN_LENGTH,
  KYC_EXPIRES_DAYS_DEFAULT,
  type SubmitKycInput,
  type ApproveKycInput,
  type RejectKycInput,
  type ManualReviewKycInput,
  type ExpireKycInput,
  type ResubmitKycInput,
  type SubmitKybInput,
  type ApproveKybInput,
  type RejectKybInput,
  type ManualReviewKybInput,
  type ExpireKybInput,
  type ResubmitKybInput,
  type ListKycInput,
  type ListKybInput,
  type ListReviewLogInput,
} from './services/kyc-service';

// ============================================================
// Permission Service - 工业级 RBAC + ABAC 实现
// ============================================================

// Permission 状态机 + 工具
export {
  ROLE_STATUS,
  ALL_ROLE_STATUSES,
  TERMINAL_ROLE_STATUSES,
  ROLE_STATUS_TRANSITIONS,
  PERMISSION_STATUS,
  ALL_PERMISSION_STATUSES,
  TERMINAL_PERMISSION_STATUSES,
  PERMISSION_STATUS_TRANSITIONS,
  ROLE_PERMISSION_STATUS,
  ALL_ROLE_PERMISSION_STATUSES,
  ROLE_PERMISSION_STATUS_TRANSITIONS,
  USER_ROLE_STATUS,
  ALL_USER_ROLE_STATUSES,
  USER_ROLE_STATUS_TRANSITIONS,
  USER_PERMISSION_STATUS,
  ALL_USER_PERMISSION_STATUSES,
  USER_PERMISSION_STATUS_TRANSITIONS,
  POLICY_STATUS,
  ALL_POLICY_STATUSES,
  POLICY_STATUS_TRANSITIONS,
  ROLE_TYPE,
  ALL_ROLE_TYPES,
  PERMISSION_TYPE,
  ALL_PERMISSION_TYPES,
  SCOPE_TYPE,
  ALL_SCOPE_TYPES,
  PERMISSION_EFFECT,
  POLICY_EFFECT,
  ACCESS_DECISION,
  // 工具
  isValidRoleStatus,
  isValidPermissionStatus,
  isValidUserRoleStatus,
  isValidUserPermissionStatus,
  isValidPolicyStatus,
  isTerminalRoleStatus,
  isTerminalPermissionStatus,
  canTransitRoleStatus,
  canTransitPermissionStatus,
  canTransitRolePermissionStatus,
  canTransitUserRoleStatus,
  canTransitUserPermissionStatus,
  canTransitPolicyStatus,
  assertTransitRoleStatus,
  assertTransitPermissionStatus,
  assertTransitRolePermissionStatus,
  assertTransitUserRoleStatus,
  assertTransitUserPermissionStatus,
  assertTransitPolicyStatus,
  nextRoleStatuses,
  nextPermissionStatuses,
  nextUserRoleStatuses,
  isRoleUsable,
  isPermissionUsable,
  isUserRoleActive,
  isUserPermissionActive,
  isValidRoleCode,
  isValidPermissionCode,
  isValidPolicyCode,
  // 类型
  type FjnRoleStatus,
  type FjnPermissionStatus,
  type FjnRolePermissionStatus,
  type FjnUserRoleStatus,
  type FjnUserPermissionStatus,
  type FjnPolicyStatus,
  type FjnRoleType,
  type FjnPermissionType,
  type FjnScopeType,
  type FjnPermissionEffect,
  type FjnPolicyEffect,
  type FjnAccessDecision,
} from './services/permission-state-machine';

// Permission 事件
export {
  PERMISSION_EVENTS,
  ALL_PERMISSION_EVENTS,
  PERMISSION_EVENT_SOURCES,
  ALL_PERMISSION_EVENT_SOURCES,
  type FjnPermissionEventName,
  type FjnPermissionEventSource,
  type RoleCreatedPayload,
  type RoleUpdatedPayload,
  type RoleDisabledPayload,
  type RoleEnabledPayload,
  type RoleDeprecatedPayload,
  type PermissionCreatedPayload,
  type PermissionUpdatedPayload,
  type PermissionDisabledPayload,
  type RolePermissionGrantedPayload,
  type RolePermissionRevokedPayload,
  type UserRoleAssignedPayload,
  type AccessPolicyCreatedPayload,
  type FjnPermissionEventPayloadMap,
} from './services/permission-events';

// Permission 错误
export {
  PERMISSION_ERROR_CODES,
  type FjnPermissionErrorCode,
  FjnPermissionError,
  FjnRoleNotFoundError,
  FjnRoleAlreadyExistsError,
  FjnRoleCodeInvalidError,
  FjnRoleNameRequiredError,
  FjnRoleStatusInvalidError,
  FjnRoleSystemProtectedError,
  FjnRoleCannotDeleteError,
  FjnRoleDisabledError,
  FjnRoleDeprecatedError,
  FjnPermissionNotFoundError,
  FjnPermissionAlreadyExistsError,
  FjnPermissionCodeInvalidError,
  FjnPermissionNameRequiredError,
  FjnPermissionStatusInvalidError,
  FjnPermissionSystemProtectedError,
  FjnPermissionDisabledError,
  FjnPermissionResourceRequiredError,
  FjnPermissionActionRequiredError,
  FjnRolePermissionAlreadyGrantedError,
  FjnRolePermissionNotGrantedError,
  FjnRolePermissionRevokedError,
  FjnRolePermissionScopeInvalidError,
  FjnRolePermissionGrantorRequiredError,
  FjnUserRoleNotFoundError,
  FjnUserRoleAlreadyAssignedError,
  FjnUserRoleRevokedError,
  FjnUserRoleDisabledError,
  FjnUserRoleGrantorRequiredError,
  FjnUserRoleScopeInvalidError,
  FjnUserRoleExpiresInvalidError,
  FjnUserPermissionNotFoundError,
  FjnUserPermissionAlreadyGrantedError,
  FjnUserPermissionRevokedError,
  FjnUserPermissionGrantorRequiredError,
  FjnUserPermissionScopeInvalidError,
  FjnUserPermissionEffectInvalidError,
  FjnPolicyNotFoundError,
  FjnPolicyAlreadyExistsError,
  FjnPolicyCodeInvalidError,
  FjnPolicyNameRequiredError,
  FjnPolicyStatusInvalidError,
  FjnPolicyConditionsInvalidError,
  FjnPolicyEffectInvalidError,
  FjnPolicyActionsRequiredError,
  FjnPolicySystemProtectedError,
  FjnPolicyValidityInvalidError,
  FjnAccessDeniedError,
  FjnEvaluationFailedError,
  FjnResourceNotSpecifiedError,
  FjnActionNotSpecifiedError,
  FjnScopeNotAllowedError,
  FjnEffectInvalidError,
  FjnPermissionInternalError,
} from './services/permission-errors';

// Permission Service
export {
  FjnPermissionService,
  PERMISSION_DEFAULT_EXPIRES_DAYS,
  type CreateRoleInput,
  type UpdateRoleInput,
  type ChangeRoleStatusInput,
  type CreatePermissionInput,
  type UpdatePermissionInput,
  type GrantRolePermissionInput,
  type RevokeRolePermissionInput,
  type AssignUserRoleInput,
  type RevokeUserRoleInput,
  type GrantUserPermissionInput,
  type RevokeUserPermissionInput,
  type CreatePolicyInput,
  type UpdatePolicyInput,
  type EvaluateAccessInput,
  type AccessDecisionResult,
  type ListRoleInput,
  type ListPermissionInput,
  type ListUserRoleInput,
  type ListAccessLogInput,
} from './services/permission-service';

// ============================================================
// Region Service - 三级地区 + 限制 + IP Geo（阶段I-任务3）
// ============================================================

// Region Service 状态机
export {
  // 状态常量
  REGION_STATUS,
  RESTRICTION_STATUS,
  IP_GEO_STATUS,
  // 状态流转
  REGION_STATUS_TRANSITIONS,
  ALL_REGION_STATUSES,
  TERMINAL_REGION_STATUSES,
  RESTRICTION_STATUS_TRANSITIONS,
  ALL_RESTRICTION_STATUSES,
  IP_GEO_STATUS_TRANSITIONS,
  ALL_IP_GEO_STATUSES,
  // 通用枚举
  REGION_LEVEL,
  ALL_REGION_LEVELS,
  REGION_LEVEL_NUMBER,
  REGION_LEVEL_CHILD,
  RESTRICTION_TYPE,
  ALL_RESTRICTION_TYPES,
  RESTRICTION_SOURCE,
  ALL_RESTRICTION_SOURCES,
  IP_VERSION,
  ALL_IP_VERSIONS,
  // 工具函数
  isValidRegionStatus,
  isValidRestrictionStatus,
  isValidIpGeoStatus,
  isValidRegionLevel,
  isValidRestrictionType,
  isValidRestrictionSource,
  isValidIpVersion,
  isTerminalRegionStatus,
  canTransitRegionStatus,
  canTransitRestrictionStatus,
  canTransitIpGeoStatus,
  assertTransitRegionStatus,
  assertTransitRestrictionStatus,
  assertTransitIpGeoStatus,
  nextRegionStatuses,
  nextRestrictionStatuses,
  isRegionUsable,
  isRestrictionActive,
  isValidCountryCode as isValidRegionCountryCode,
  isValidSubdivisionCode as isValidRegionSubdivisionCode,
  isValidRegionCode as isValidRegionCodeFormat,
  childRegionLevel,
  parentRegionLevel,
  isValidParentLevel,
  // 类型
  type FjnRegionStatus,
  type FjnRestrictionStatus,
  type FjnIpGeoStatus,
  type FjnRegionLevel,
  type FjnRestrictionType,
  type FjnRestrictionSource,
  type FjnIpVersion,
} from './services/region-state-machine';

// Region Service 事件
export {
  REGION_EVENTS,
  REGION_EVENT_SOURCES,
  ALL_REGION_EVENTS,
  ALL_REGION_EVENT_SOURCES,
  type FjnRegionEventName,
  type FjnRegionEventSource,
  type RegionCreatedPayload,
  type RegionUpdatedPayload,
  type RegionDisabledPayload,
  type RegionDeprecatedPayload,
  type RestrictionAddedPayload,
  type RestrictionRemovedPayload,
  type RestrictionExpiredPayload,
  type RestrictionMatchedPayload,
  type IpGeoRegisteredPayload,
  type IpGeoResolvedPayload,
  type FjnRegionEventPayloadMap,
  type FjnRegionEventPayload,
} from './services/region-events';

// Region Service 错误
export {
  REGION_ERROR_CODES,
  type FjnRegionErrorCode,
  FjnRegionError,
  FjnRegionNotFoundError,
  FjnRegionAlreadyExistsError,
  FjnRegionCodeInvalidError,
  FjnRegionNameRequiredError,
  FjnRegionLevelInvalidError,
  FjnRegionStatusInvalidError,
  FjnRegionCountryCodeInvalidError,
  FjnRegionSubdivisionCodeInvalidError,
  FjnRegionParentRequiredError,
  FjnRegionParentNotFoundError,
  FjnRegionParentLevelInvalidError,
  FjnRegionHasChildrenError,
  FjnRegionSystemProtectedError,
  FjnRegionCircularReferenceError,
  FjnRegionDisabledError,
  FjnRegionDeprecatedError,
  FjnRegionRestrictionNotFoundError,
  FjnRegionRestrictionAlreadyExistsError,
  FjnRegionRestrictionTypeInvalidError,
  FjnRegionRestrictionSourceInvalidError,
  FjnRegionRestrictionReasonRequiredError,
  FjnRegionRestrictionExpiresInvalidError,
  FjnRegionRestrictionAlreadyDisabledError,
  FjnRegionRestrictionAlreadyExpiredError,
  FjnIpGeoNotFoundError,
  FjnIpGeoAlreadyExistsError,
  FjnIpGeoInvalidIpv4Error,
  FjnIpGeoInvalidIpv6Error,
  FjnIpGeoRangeOverlapError,
  FjnIpGeoRangeInvalidError,
  FjnIpGeoVersionInvalidError,
  FjnIpGeoNotResolvedError,
  /** 与 ../errors 中的同名类区分 */
  FjnRegionRestrictedError as FjnRegionServiceRestrictedError,
  FjnRegionAllowlistMissError,
  FjnRegionKycLevelInsufficientError,
  FjnRegionRiskHighError,
} from './services/region-errors';

// Region Service
export {
  FjnRegionService,
  createFjnRegionService,
  REGION_DEFAULT_EXPIRES_DAYS,
  type CreateRegionInput,
  type UpdateRegionInput,
  type ChangeRegionStatusInput,
  type ListRegionInput,
  type AddRestrictionInput,
  type ChangeRestrictionStatusInput,
  type ListRestrictionInput,
  type RegisterIpGeoInput,
  type ListIpGeoInput,
  type ResolveIpInput,
  type CheckRestrictionContext,
  type RestrictionCheckResult,
  type IpResolveResult,
  type RegionTreeNode,
} from './services/region-service';

// ============================================================
// 阶段I-任务4：Device Service（用户设备管理）
//  - Fingerprint / UserDevice / Blacklist / RiskAssessment / Challenge
//  - 11 个事件常量 + 5 个状态机 + 35+ 错误码
// ============================================================

// Device 状态机 + 工具
export {
  USER_DEVICE_STATUS,
  ALL_USER_DEVICE_STATUSES,
  TERMINAL_USER_DEVICE_STATUSES,
  USER_DEVICE_STATUS_TRANSITIONS,
  BLACKLIST_STATUS,
  ALL_BLACKLIST_STATUSES,
  BLACKLIST_STATUS_TRANSITIONS,
  RISK_ASSESSMENT_STATUS,
  ALL_RISK_ASSESSMENT_STATUSES,
  RISK_ASSESSMENT_STATUS_TRANSITIONS,
  CHALLENGE_STATUS,
  ALL_CHALLENGE_STATUSES,
  TERMINAL_CHALLENGE_STATUSES,
  CHALLENGE_STATUS_TRANSITIONS,
  DEVICE_TYPE,
  ALL_DEVICE_TYPES,
  DEVICE_RISK_LEVEL,
  ALL_DEVICE_RISK_LEVELS,
  DEVICE_RISK_LEVEL_WEIGHT,
  CHALLENGE_TYPE,
  ALL_CHALLENGE_TYPES,
  CHALLENGE_TRIGGER,
  ALL_CHALLENGE_TRIGGERS,
  BLACKLIST_REASON,
  ALL_BLACKLIST_REASONS,
  BLACKLIST_SOURCE as DEVICE_BLACKLIST_SOURCE,
  ALL_BLACKLIST_SOURCES as ALL_DEVICE_BLACKLIST_SOURCES,
  RISK_FACTOR,
  ALL_RISK_FACTORS,
  RISK_FACTOR_WEIGHT,
  TRUST_ACTION,
  ALL_TRUST_ACTIONS,
  isValidUserDeviceStatus,
  isValidBlacklistStatus,
  isValidRiskAssessmentStatus,
  isValidChallengeStatus,
  isValidDeviceType,
  isValidDeviceRiskLevel,
  isValidChallengeType,
  isValidChallengeTrigger,
  isValidBlacklistReason,
  isValidBlacklistSource as isValidDeviceBlacklistSource,
  isValidRiskFactor,
  isValidTrustAction,
  isTerminalUserDeviceStatus,
  isTerminalChallengeStatus,
  canTransitUserDeviceStatus,
  canTransitBlacklistStatus,
  canTransitRiskAssessmentStatus,
  canTransitChallengeStatus,
  assertTransitUserDeviceStatus,
  assertTransitBlacklistStatus as assertTransitDeviceBlacklistStatus,
  assertTransitRiskAssessmentStatus,
  assertTransitChallengeStatus,
  nextUserDeviceStatuses,
  nextChallengeStatuses,
  isUserDeviceUsable,
  isBlacklistActive,
  isChallengePending,
  riskLevelScore,
  riskFactorScore,
  calcDeviceRiskLevel,
  isValidFingerprint,
  isValidDeviceName,
  isValidRiskScore,
  DEVICE_CHALLENGE_DEFAULT_EXPIRES_MINUTES,
  DEVICE_CHALLENGE_DEFAULT_MAX_ATTEMPTS,
  DEVICE_USER_MAX_DEVICES,
  DEVICE_TRUST_AUTO_THRESHOLD,
  DEVICE_CHALLENGE_AUTO_THRESHOLD,
  DEVICE_BLOCK_AUTO_THRESHOLD,
  DEVICE_BLACKLIST_DEFAULT_EXPIRES_DAYS,
  type FjnUserDeviceStatus,
  type FjnBlacklistStatus,
  type FjnRiskAssessmentStatus,
  type FjnChallengeStatus,
  type FjnDeviceType,
  type FjnDeviceRiskLevel,
  type FjnChallengeType,
  type FjnChallengeTrigger,
  type FjnBlacklistReason,
  type FjnBlacklistSource,
  type FjnTrustAction,
  type FjnRiskFactor,
} from './services/device-state-machine';

// Device 事件
export {
  DEVICE_EVENTS,
  ALL_DEVICE_EVENTS,
  DEVICE_EVENT_SOURCES,
  ALL_DEVICE_EVENT_SOURCES,
  type FjnDeviceEventName,
  type FjnDeviceEventSource,
  type DeviceBoundPayload,
  type DeviceTrustedPayload,
  type DeviceBlockedPayload,
  type DeviceRevokedPayload,
  type DeviceHeartbeatPayload,
  type DeviceBlacklistedPayload,
  type DeviceUnblacklistedPayload,
  type DeviceRiskScoredPayload,
  type ChallengeIssuedPayload,
  type ChallengeVerifiedPayload,
  type ChallengeFailedPayload,
  type FjnDeviceEventPayloadMap,
  type FjnDeviceEventPayload,
} from './services/device-events';

// Device 错误
export {
  DEVICE_ERROR_CODES,
  type FjnDeviceErrorCode,
  FjnDeviceError,
  FjnUserDeviceNotFoundError,
  FjnUserDeviceAlreadyBoundError,
  FjnUserDeviceLimitExceededError,
  FjnUserDeviceStatusInvalidError,
  FjnUserDeviceRevokedError,
  FjnUserDeviceBlockedError,
  FjnUserDeviceHeartbeatExpiredError,
  FjnUserDeviceNameInvalidError,
  FjnTrustLogNotFoundError,
  FjnTrustAlreadyAppliedError,
  FjnTrustRevokeNotAllowedError,
  FjnDeviceBlacklistNotFoundError,
  FjnDeviceBlacklistAlreadyExistsError,
  FjnDeviceBlacklistMatchedError,
  FjnDeviceBlacklistReasonInvalidError,
  FjnDeviceBlacklistSourceInvalidError,
  FjnDeviceBlacklistRefNoRequiredError,
  FjnDeviceBlacklistExpiresInvalidError,
  FjnDeviceBlacklistAlreadyDisabledError,
  FjnDeviceRiskAssessmentNotFoundError,
  FjnDeviceRiskAssessmentAlreadyActionedError,
  FjnDeviceRiskScoreInvalidError,
  FjnDeviceRiskFactorInvalidError,
  FjnDeviceChallengeNotFoundError,
  FjnDeviceChallengeAlreadyVerifiedError,
  FjnDeviceChallengeAlreadyFailedError,
  FjnDeviceChallengeExpiredError,
  FjnDeviceChallengeCancelledError,
  FjnDeviceChallengeCodeMismatchError,
  FjnDeviceChallengeMaxAttemptsExceededError,
  FjnDeviceChallengeTypeInvalidError,
  FjnDeviceChallengeTriggerInvalidError,
  FjnDeviceChallengeTargetRequiredError,
  FjnDeviceChallengeNotPendingError,
  FjnDeviceFingerprintNotFoundError,
  FjnDeviceFingerprintInvalidError,
  FjnDeviceFingerprintAlreadyExistsError,
} from './services/device-errors';

// Device Service
export {
  FjnDeviceService,
  createFjnDeviceService,
  DEVICE_DEFAULT_USER_MAX_DEVICES,
  type UpsertFingerprintInput,
  type BindDeviceInput,
  type DeviceHeartbeatInput,
  type ListUserDeviceInput,
  type ChangeDeviceStatusInput,
  type AddBlacklistInput,
  type ListBlacklistInput,
  type CheckBlacklistInput,
  type AssessDeviceRiskInput,
  type ListRiskAssessmentInput,
  type ActionRiskAssessmentInput,
  type IssueChallengeInput,
  type VerifyChallengeInput,
  type ChangeChallengeStatusInput,
  type ListChallengeInput,
  type BindDeviceResult,
  type RiskAssessmentResult,
  type BlacklistCheckResult,
} from './services/device-service';

// ============================================================
// 阶段I-任务7：Points Service（FJ369 Points / cFJ369 积分系统）
//  - Account / Ledger / Freeze / Reversal / Rule / Snapshot
//  - 12 个事件常量 + 4 个状态机 + 50+ 错误码
// ============================================================

// Points 状态机 + 工具
export {
  POINTS_ACCOUNT_STATUS,
  ALL_POINTS_ACCOUNT_STATUSES,
  TERMINAL_POINTS_ACCOUNT_STATUSES,
  POINTS_ACCOUNT_STATUS_TRANSITIONS,
  POINTS_FREEZE_STATUS,
  ALL_POINTS_FREEZE_STATUSES,
  POINTS_FREEZE_STATUS_TRANSITIONS,
  POINTS_REVERSAL_STATUS,
  ALL_POINTS_REVERSAL_STATUSES,
  POINTS_REVERSAL_STATUS_TRANSITIONS,
  POINTS_RULE_STATUS,
  ALL_POINTS_RULE_STATUSES,
  POINTS_RULE_STATUS_TRANSITIONS,
  POINTS_ASSET_TYPE,
  ALL_POINTS_ASSET_TYPES,
  POINTS_DIRECTION,
  POINTS_CHANGE_TYPE,
  ALL_POINTS_CHANGE_TYPES,
  POINTS_SOURCE_TYPE,
  ALL_POINTS_SOURCE_TYPES,
  POINTS_BIZ_TYPE,
  ALL_POINTS_BIZ_TYPES,
  POINTS_SNAPSHOT_TYPE,
  ALL_POINTS_SNAPSHOT_TYPES,
  POINTS_RISK_STATUS,
  ALL_POINTS_RISK_STATUSES,
  FJ369_STANDARD_GRANT_POINTS,
  CFJ369_TO_TFJ369_DEFAULT_RATIO,
  TPOINTS_CONVERSION_FEE_RATE,
  POINTS_AMOUNT_PRECISION,
  isValidPointsAccountStatus,
  isValidPointsFreezeStatus,
  isValidPointsReversalStatus,
  isValidPointsRuleStatus,
  isValidPointsAssetType,
  isValidPointsChangeType,
  isValidPointsSourceType,
  isValidPointsBizType,
  isValidPointsSnapshotType,
  isValidPointsRiskStatus,
  canTransitPointsAccountStatus,
  canTransitPointsFreezeStatus,
  canTransitPointsReversalStatus,
  canTransitPointsRuleStatus,
  assertTransitPointsAccountStatus,
  assertTransitPointsFreezeStatus,
  assertTransitPointsReversalStatus,
  assertTransitPointsRuleStatus,
  isDecreaseChangeType,
  isIncreaseChangeType,
  isPointsAccountUsable,
  isPointsFreezeActive,
  type FjnPointsAccountStatus,
  type FjnPointsFreezeStatus,
  type FjnPointsReversalStatus,
  type FjnPointsRuleStatus,
  type FjnPointsAssetType,
  type FjnPointsChangeType,
  type FjnPointsSourceType,
  type FjnPointsBizType,
  type FjnPointsSnapshotType,
  type FjnPointsRiskStatus,
} from './services/points-state-machine';

// Points 事件
export {
  POINTS_EVENTS,
  ALL_POINTS_EVENTS,
  POINTS_EVENT_SOURCES,
  ALL_POINTS_EVENT_SOURCES,
  type PointsAccountOpenedPayload,
  type PointsAccountFrozenPayload,
  type PointsAccountClosedPayload,
  type PointsEarnedPayload,
  type PointsConsumedPayload,
  type PointsFrozenPayload,
  type PointsUnfrozenPayload,
  type PointsReversedPayload,
  type PointsRuleCreatedPayload,
  type PointsRuleActivatedPayload,
  type PointsSnapshotCreatedPayload,
  type PointsExpiredPayload,
  type FjnPointsEventSource,
} from './services/points-events';

// Points 错误
export {
  POINTS_ERROR_CODES,
  FjnPointsError,
  FjnPointsAccountNotFoundError,
  FjnPointsAccountExistsError,
  FjnPointsAccountFrozenError,
  FjnPointsAccountClosedError,
  FjnPointsAccountStatusInvalidError,
  FjnPointsLedgerNotFoundError,
  FjnPointsLedgerAmountInvalidError,
  FjnPointsLedgerBalanceMismatchError,
  FjnPointsLedgerDuplicateError,
  FjnPointsLedgerDirectionInvalidError,
  FjnPointsLedgerChangeTypeInvalidError,
  FjnPointsLedgerSourceTypeInvalidError,
  FjnPointsLedgerBizTypeInvalidError,
  FjnPointsInsufficientAvailableError,
  FjnPointsInsufficientFrozenError,
  FjnPointsInsufficientLockedError,
  FjnPointsAmountMustBePositiveError,
  FjnPointsAmountTooLargeError,
  FjnPointsBalanceNegativeError,
  FjnPointsFreezeNotFoundError,
  FjnPointsFreezeNotActiveError,
  FjnPointsFreezeAmountExceedsAvailableError,
  FjnPointsFreezeReasonRequiredError,
  FjnPointsFreezeExpiresInvalidError,
  FjnPointsUnfreezeAmountExceedsFreezeError,
  FjnPointsReversalNotFoundError,
  FjnPointsReversalNotPendingError,
  FjnPointsReversalAmountExceedsOriginalError,
  FjnPointsReversalReasonRequiredError,
  FjnPointsReversalDuplicateError,
  FjnPointsRuleNotFoundError,
  FjnPointsRuleExistsError,
  FjnPointsRuleNotActiveError,
  FjnPointsRuleNotApprovedError,
  FjnPointsRuleEffectiveInvalidError,
  FjnPointsRuleVersionInvalidError,
  FjnPointsRuleContentInvalidError,
  FjnPointsRuleStatusInvalidError,
  FjnPointsSnapshotNotFoundError,
  FjnPointsSnapshotFailedError,
  FjnPointsSnapshotTypeInvalidError,
  FjnPointsRiskBlockedError,
  FjnPointsRiskHoldError,
  FjnPointsUserIdRequiredError,
  FjnPointsAssetTypeInvalidError,
  FjnPointsGrantAmountExceedsRuleError,
  FjnPointsConversionRatioInvalidError,
  FjnPointsKycLevelInsufficientError,
  FjnPointsRegionRestrictedError,
  type FjnPointsErrorCode,
} from './services/points-errors';

// Points Service
export {
  FjnPointsService,
  createFjnPointsService,
  type OpenPointsAccountInput,
  type EarnPointsInput,
  type ConsumePointsInput,
  type FreezePointsInput,
  type UnfreezePointsInput,
  type RevokeFreezeInput,
  type ReversePointsInput,
  type CreatePointsRuleInput,
  type CreatePointsSnapshotInput,
  type ListPointsInput,
  type PointsSummary,
  type PointsBalanceTrace,
} from './services/points-service';

// ============================================================
// NFT Service 已迁移到 Solana-first 重构（工业级最终方案 §5.3）
// 迁移位置：src/lib/solana/nft/solana-nft-service.ts
// 迁移时间：2026-07-01
// ============================================================

/** 迁移说明常量（业务侧可读） */
export const FJN_NFT_SOLANA_FIRST_MIGRATION_NOTE =
  'WinePass NFT / Bottle NFT / Mall NFT / Game NFT / Sports NFT / Club NFT 已统一迁移到 Solana Metaplex，Service 位置：src/lib/solana/nft/solana-nft-service.ts。FJN 域内旧的 nft-service / nft-state-machine / nft-events / nft-errors 已归档到 docs/_trash/2026-07-01-solana-first-重构/。' as const;

// ============================================================
// WinePass NFT Service（Solana 域内，369 权益 NFT）
// 工业级实现：文档 §5.5.3
// ============================================================
export {
  WINEPASS_NFT_TYPE,
  WINEPASS_COLLECTION_STATUS,
  WINEPASS_ASSET_STATUS,
  WINEPASS_UPGRADE_STATUS,
  WINEPASS_BENEFIT_TYPE,
  WINEPASS_TRANSFER_TYPE,
  WINEPASS_CHAIN_TYPE,
  WINEPASS_PAYMENT_TYPE,
  WINEPASS_CHAIN_RECORD_STATUS,
  WINEPASS_DEFAULT_CHAIN_ID,
  WINEPASS_DEFAULT_CLUSTER,
  WINEPASS_MIN_LEVEL,
  WINEPASS_MAX_LEVEL,
  WINEPASS_DEFAULT_LEVEL,
  WINEPASS_UPGRADE_BASE_COST,
  isValidWinepassNftType,
  isValidWinepassCollectionStatus,
  isValidWinepassAssetStatus,
  isValidWinepassUpgradeStatus,
  isValidWinepassBenefitType,
  type FjnWinepassNftType,
  type FjnWinepassCollectionStatus,
  type FjnWinepassAssetStatus,
  type FjnWinepassUpgradeStatus,
  type FjnWinepassBenefitType,
  type FjnWinepassTransferType,
  type FjnWinepassChainType,
  type FjnWinepassPaymentType,
} from './services/winepass-nft-state-machine';

export {
  WINEPASS_NFT_EVENTS,
  WINEPASS_NFT_EVENT_SOURCES,
  type FjnWinepassNftEvent,
  type FjnWinepassNftEventSource,
  type WinepassCollectionCreatedPayload,
  type WinepassAssetMintedPayload,
  type WinepassAssetUpgradedPayload,
  type FjnWinepassNftEventPayload,
} from './services/winepass-nft-events';

export {
  WINEPASS_NFT_ERROR_CODES,
  type FjnWinepassNftErrorCode,
  FjnWinepassNftError,
  WinepassCollectionNotFoundError,
  WinepassCollectionExistsError,
  WinepassCollectionPausedError,
  WinepassCollectionSupplyExceededError,
  WinepassCollectionNameRequiredError,
  WinepassCollectionSymbolInvalidError,
  WinepassCollectionTypeInvalidError,
  WinepassCollectionDeprecatedError,
  WinepassAssetNotFoundError,
  WinepassAssetNotOwnedError,
  WinepassAssetNotMintedError,
  WinepassAssetAlreadyMintedError,
  WinepassAssetFrozenError,
  WinepassAssetBurnedError,
  WinepassAssetNotUpgradableError,
  WinepassAssetMaxLevelError,
  WinepassAssetInvalidLevelError,
  WinepassAssetTokenIdMissingError,
  WinepassAssetTransferRestrictedError,
  WinepassUpgradeNotFoundError,
  WinepassUpgradeAlreadyPaidError,
  WinepassUpgradeNotExecutableError,
  WinepassUpgradeNotCancellableError,
  WinepassUpgradeAmountInvalidError,
  WinepassUpgradePaymentInvalidError,
  WinepassBenefitTypeInvalidError,
  WinepassBenefitAmountInvalidError,
  WinepassOwnershipNotFoundError,
  WinepassOwnershipTransferNotAllowedError,
  WinepassChainRecordNotFoundError,
  WinepassChainRecordTxHashDuplicateError,
  WinepassSolanaNftMintFailedError,
  WinepassSolanaNftTransferFailedError,
  WinepassSolanaNftBurnFailedError,
} from './services/winepass-nft-errors';

export {
  FjnWinepassNftService,
  type CreateWinepassCollectionInput,
  type MintWinepassAssetInput,
  type TransferWinepassAssetInput,
  type BurnWinepassAssetInput,
  type FreezeWinepassAssetInput,
  type UnfreezeWinepassAssetInput,
  type CreateWinepassUpgradeInput,
  type PayWinepassUpgradeInput,
  type ExecuteWinepassUpgradeInput,
  type GrantWinepassBenefitInput,
  type RecordWinepassChainInput,
  type ListWinepassAssetsInput,
  type WinepassCollectionSummary,
  type WinepassAssetSummary,
  type WinepassUpgradeSummary,
} from './services/winepass-nft-service';

// ============================================================
// tFJ369 Service（369 可流通积分，Solana SPL Token 集成）
// 工业级实现：文档 §5.5.2
// ============================================================
export {
  TPOINTS_ACCOUNT_STATUS,
  TPOINTS_LEDGER_DIRECTION,
  TPOINTS_LEDGER_CHANGE_TYPE,
  TPOINTS_LOCK_TYPE,
  TPOINTS_LOCK_STATUS,
  TPOINTS_CONVERSION_STATUS,
  TPOINTS_MEMBER_LEVEL,
  TPOINTS_RISK_STATUS,
  TPOINTS_AMOUNT_PRECISION,
  TPOINTS_DEFAULT_CONVERT_RATIO,
  isValidTPointsAccountStatus,
  isValidTPointsChangeType,
  isValidTPointsLockType,
  isValidTPointsLockStatus,
  isValidTPointsConversionStatus,
  isValidTPointsMemberLevel,
  isValidTPointsRiskStatus,
  type FjnTPointsAccountStatus,
  type FjnTPointsChangeType,
  type FjnTPointsLockType,
  type FjnTPointsLockStatus,
  type FjnTPointsConversionStatus,
  type FjnTPointsMemberLevel,
  type FjnTPointsRiskStatus,
} from './services/tfj369-state-machine';

export {
  TFJ369_EVENTS,
  TFJ369_EVENT_SOURCES,
  type FjnTfj369Event,
} from './services/tfj369-events';

export {
  TFJ369_ERROR_CODES,
  type FjnTfj369ErrorCode,
  Tfj369UserIdRequiredError,
  Tfj369AccountNotFoundError,
  Tfj369AccountFrozenError,
  Tfj369AccountClosedError,
  Tfj369AmountInvalidError,
  Tfj369BalanceInsufficientError,
  Tfj369LockNotFoundError,
  Tfj369ConversionNotFoundError,
  Tfj369ConversionRegionBlockedError,
  Tfj369ConversionRiskBlockedError,
  Tfj369ConversionKycRequiredError,
  Tfj369RiskBlockedError,
  Tfj369SolanaMintFailedError,
  Tfj369SolanaBurnFailedError,
} from './services/tfj369-errors';

export {
  FjnTfj369Service,
  createFjnTfj369Service,
  type OpenTfj369AccountInput,
  type MintTfj369Input,
  type BurnTfj369Input,
  type LockTfj369Input,
  type UnlockTfj369Input,
  type RequestConversionInput,
  type ApproveConversionInput,
  type ExecuteConversionInput,
} from './services/tfj369-service';

// ============================================================
// Release Service（生态释放 + Solana Anchor Claim）
// 工业级实现：文档 §5.5.4
// ============================================================
export {
  RELEASE_POOL_TYPE,
  RELEASE_POOL_STATUS,
  RELEASE_CALCULATION_STATUS,
  RELEASE_CLAIM_STATUS,
  RELEASE_RISK_STATUS,
  RELEASE_PAYMENT_TYPE,
  RELEASE_CLAIM_DEFAULT_EXPIRES_DAYS,
  RELEASE_DEFAULT_CURRENCY,
  RELEASE_DEFAULT_CHAIN_ID,
  RELEASE_POOL_STATUS_TRANSITIONS,
  isValidReleasePoolType,
  isValidReleasePoolStatus,
  isValidReleaseCalculationStatus,
  isValidReleaseClaimStatus,
  isValidReleaseRiskStatus,
  isValidReleasePaymentType,
  canTransitReleasePoolStatus,
  type FjnReleasePoolType,
  type FjnReleasePoolStatus,
  type FjnReleaseCalculationStatus,
  type FjnReleaseClaimStatus,
  type FjnReleaseRiskStatus,
  type FjnReleasePaymentType,
} from './services/release-state-machine';

export {
  RELEASE_EVENTS,
  RELEASE_EVENT_SOURCES,
  type FjnReleaseEvent,
  type FjnReleaseEventSource,
  type ReleasePoolCreatedPayload,
  type ReleasePoolClaimOpenPayload,
  type ReleaseClaimSucceededPayload,
  type FjnReleaseEventPayload,
} from './services/release-events';

export {
  RELEASE_ERROR_CODES,
  type FjnReleaseErrorCode,
  FjnReleaseError,
  ReleasePoolNotFoundError,
  ReleasePoolExistsError,
  ReleasePoolStatusInvalidError,
  ReleasePoolNotApprovableError,
  ReleasePoolNotClaimableError,
  ReleasePoolAlreadyClosedError,
  ReleasePoolAlreadyCancelledError,
  ReleasePoolTotalInvalidError,
  ReleasePoolPeriodInvalidError,
  ReleasePoolNameRequiredError,
  ReleasePoolTypeInvalidError,
  ReleasePoolApproverRequiredError,
  ReleasePoolMerkleRootRequiredError,
  ReleaseCalculationNotFoundError,
  ReleaseCalculationExistsError,
  ReleaseCalculationStatusInvalidError,
  ReleaseCalculationNotApprovableError,
  ReleaseCalculationRatioInvalidError,
  ReleaseCalculationAmountInvalidError,
  ReleaseCalculationMonthlyCapExceededError,
  ReleaseCalculationRiskBlockedError,
  ReleaseCalculationUserIdRequiredError,
  ReleaseCalculationEffectivePowerInvalidError,
  ReleaseCalculationNetworkTotalInvalidError,
  ReleaseCalculationPrecisionLossError,
  ReleaseClaimNotFoundError,
  ReleaseClaimStatusInvalidError,
  ReleaseClaimNotClaimableError,
  ReleaseClaimAlreadyClaimedError,
  ReleaseClaimExpiredError,
  ReleaseClaimRiskHoldError,
  ReleaseClaimMerkleProofInvalidError,
  ReleaseClaimTxHashDuplicateError,
  ReleaseClaimAmountExceedsClaimableError,
  ReleaseClaimAmountInvalidError,
  ReleaseClaimBlockNumberInvalidError,
  ReleaseClaimSolanaFailedError,
  ReleaseClaimUserQuotaExceededError,
  ReleaseQuotaNotFoundError,
  ReleaseQuotaInsufficientError,
  ReleaseQuotaPeriodInvalidError,
  ReleaseUserIdRequiredError,
  ReleaseCurrencyInvalidError,
} from './services/release-errors';

export {
  FjnReleaseService,
  type CreateReleasePoolInput,
  type ApproveReleasePoolInput,
  type MarkSnapshotReadyInput,
  type MarkCalculatedInput,
  type MarkRiskCheckingInput,
  type OpenClaimInput,
  type ClosePoolInput as CloseReleasePoolInput,
  type CancelPoolInput as CancelReleasePoolInput,
  type CreateCalculationInput,
  type ApproveCalculationInput,
  type MarkCalculationRiskHoldInput,
  type MarkCalculationClaimableInput,
  type CreateReleaseClaimInput,
  type StartProcessingClaimInput,
  type MarkClaimSucceededInput,
  type MarkClaimFailedInput,
  type ListReleasePoolsInput,
  type ListReleaseClaimsInput,
  type ReleasePoolSummary,
  type ReleaseClaimSummary,
} from './services/release-service';

// =====================================================================
// Sports Compliance Service 状态机 + 事件 + 错误 + 主体（Step 5 #8）
// =====================================================================

export {
  SPORTS_COMPLIANCE_CHECK_TYPE,
  SPORTS_COMPLIANCE_RESULT,
  SPORTS_COMPLIANCE_RISK_DECISION,
  SPORTS_COMPLIANCE_PEP_STATUS,
  SPORTS_COMPLIANCE_SANCTIONS_LIST,
  SPORTS_COMPLIANCE_LICENSE_STATUS,
  SPORTS_COMPLIANCE_REGION_LICENSE,
  SPORTS_COMPLIANCE_DEFAULT_RISK_SCORE_BLOCK,
  SPORTS_COMPLIANCE_DEFAULT_RISK_SCORE_REVIEW,
  SPORTS_COMPLIANCE_DEFAULT_DAILY_LIMIT,
  SPORTS_COMPLIANCE_DEFAULT_PER_TX_LIMIT,
  SPORTS_COMPLIANCE_MIN_AGE,
  SPORTS_COMPLIANCE_LICENSED_KYC_LEVEL,
  SPORTS_COMPLIANCE_DEFAULT_CHAIN_ID,
  SPORTS_COMPLIANCE_FULL_CHECK_STEPS,
  isValidSportsComplianceCheckType,
  isValidSportsComplianceResult,
  isValidSportsComplianceRiskDecision,
  isValidSportsCompliancePepStatus,
  isValidSportsComplianceSanctionsList,
  isValidSportsComplianceLicenseStatus,
  type FjnSportsComplianceCheckType,
  type FjnSportsComplianceResult,
  type FjnSportsComplianceRiskDecision,
  type FjnSportsCompliancePepStatus,
  type FjnSportsComplianceSanctionsList,
  type FjnSportsComplianceLicenseStatus,
} from './services/sports-compliance-state-machine';

export {
  SPORTS_COMPLIANCE_EVENTS,
  SPORTS_COMPLIANCE_EVENT_SOURCES,
  type FjnSportsComplianceEvent,
  type FjnSportsComplianceEventSource,
  type SportsComplianceCheckCreatedPayload,
  type SportsComplianceCheckReviewedPayload,
  type SportsComplianceRegionBlockedPayload,
  type SportsComplianceSanctionsHitPayload,
  type FjnSportsComplianceEventPayload,
} from './services/sports-compliance-events';

export {
  SPORTS_COMPLIANCE_ERROR_CODES,
  FjnSportsComplianceError,
  SportsComplianceCheckNotFoundError,
  SportsComplianceCheckTypeInvalidError,
  SportsComplianceResultInvalidError,
  SportsComplianceUserIdRequiredError,
  SportsComplianceEventIdRequiredError,
  SportsComplianceRegionBlockedError,
  SportsComplianceRegionCodeInvalidError,
  SportsComplianceAgeRejectedError,
  SportsComplianceAgeInvalidError,
  SportsComplianceKycInsufficientError,
  SportsComplianceKycLevelInvalidError,
  SportsComplianceSanctionsHitError,
  SportsCompliancePepHitError,
  SportsComplianceRiskBlockedError,
  SportsComplianceRiskScoreInvalidError,
  SportsComplianceLimitExceededError,
  SportsComplianceLimitInvalidError,
  SportsComplianceReviewerRequiredError,
  SportsComplianceReviewInvalidStateError,
  SportsComplianceDecisionInvalidError,
  SportsComplianceEventNotFoundError,
  type FjnSportsComplianceErrorCode,
} from './services/sports-compliance-errors';

export {
  FjnSportsComplianceService,
  createFjnSportsComplianceService,
  type CheckRegionInput,
  type CheckAgeInput,
  type CheckKycInput,
  type CheckSanctionsPepInput,
  type CheckRiskInput,
  type CheckLimitInput,
  type CheckSportsComplianceInput,
  type ReviewCheckInput,
  type ListSportsComplianceChecksInput,
  type SportsComplianceCheckSummary,
  type RunFullComplianceResult,
} from './services/sports-compliance-service';

// =====================================================================
// Sports Pool Service 状态机 + 事件 + 错误 + 主体（Step 5 #9）
// =====================================================================

export {
  SPORTS_POOL_TYPE,
  SPORTS_POOL_STATUS,
  SPORTS_EVENT_STATUS,
  SPORTS_MARKET_TYPE,
  SPORTS_MARKET_STATUS,
  SPORTS_ENTRY_STATUS,
  SPORTS_ENTRY_PAYMENT_METHOD,
  SPORTS_ODDS_FORMAT,
  SPORTS_OUTCOME,
  SPORTS_CATEGORY,
  SPORTS_POOL_DEFAULT_CHAIN_ID,
  SPORTS_POOL_DEFAULT_CURRENCY,
  SPORTS_ODDS_PRECISION,
  SPORTS_MIN_ODDS,
  SPORTS_POOL_STATUS_TRANSITIONS,
  SPORTS_EVENT_STATUS_TRANSITIONS,
  SPORTS_MARKET_STATUS_TRANSITIONS,
  SPORTS_ENTRY_STATUS_TRANSITIONS,
  isValidSportsPoolType,
  isValidSportsPoolStatus,
  isValidSportsEventStatus,
  isValidSportsMarketType,
  isValidSportsMarketStatus,
  isValidSportsEntryStatus,
  isValidSportsEntryPaymentMethod,
  isValidSportsOddsFormat,
  isValidSportsOutcome,
  isValidSportsCategory,
  canTransitSportsPoolStatus,
  canTransitSportsEventStatus,
  canTransitSportsMarketStatus,
  canTransitSportsEntryStatus,
  type FjnSportsPoolType,
  type FjnSportsPoolStatus,
  type FjnSportsEventStatus,
  type FjnSportsMarketType,
  type FjnSportsMarketStatus,
  type FjnSportsEntryStatus,
  type FjnSportsEntryPaymentMethod,
  type FjnSportsOddsFormat,
  type FjnSportsOutcome,
  type FjnSportsCategory,
} from './services/sports-pool-state-machine';

export {
  SPORTS_POOL_EVENTS,
  SPORTS_POOL_EVENT_SOURCES,
  type FjnSportsPoolEvent,
  type FjnSportsPoolEventSource,
  type SportsPoolCreatedPayload,
  type SportsEventSettledPayload,
  type SportsEntryPlacedPayload,
  type SportsEntrySettledPayload,
  type FjnSportsPoolEventPayload,
} from './services/sports-pool-events';

export {
  SPORTS_POOL_ERROR_CODES,
  FjnSportsPoolError,
  SportsPoolNotFoundError,
  SportsPoolTypeInvalidError,
  SportsPoolStatusInvalidError,
  SportsPoolLockedError,
  SportsPoolClosedError,
  SportsPoolNameRequiredError,
  SportsEventNotFoundError,
  SportsEventStatusInvalidError,
  SportsEventNameRequiredError,
  SportsEventTimeInvalidError,
  SportsEventOutcomeInvalidError,
  SportsEventTeamsRequiredError,
  SportsMarketNotFoundError,
  SportsMarketStatusInvalidError,
  SportsMarketLockedError,
  SportsMarketTypeInvalidError,
  SportsMarketOddsInvalidError,
  SportsMarketOutcomesRequiredError,
  SportsEntryNotFoundError,
  SportsEntryStatusInvalidError,
  SportsEntryStakeInvalidError,
  SportsEntryUserIdRequiredError,
  SportsEntryPaymentMethodInvalidError,
  SportsEntryOutcomeRequiredError,
  SportsEntryAlreadySettledError,
  SportsEntryAlreadyPaidError,
  SportsEntryDuplicateError,
  SportsEntryTxHashDuplicateError,
  SportsComplianceFailedError,
  SportsComplianceRequiredError,
  SportsRiskHoldError,
  SportsOracleResultInvalidError,
  SportsOraclePublisherRequiredError,
  SportsPayoutFailedError,
  SportsRefundFailedError,
  SportsCategoryInvalidError,
  SportsPayoutAmountInvalidError,
  type FjnSportsPoolErrorCode,
} from './services/sports-pool-errors';

export {
  FjnSportsPoolService,
  createFjnSportsPoolService,
  type CreateSportsPoolInput,
  type CreateSportsEventInput,
  type CreateSportsMarketInput,
  type PlaceEntryInput,
  type MarkEntryPaidInput,
  type ConfirmEntryInput,
  type HoldEntryInput,
  type ReleaseHoldInput,
  type RefundEntryInput,
  type VoidEntryInput,
  type PublishOracleResultInput,
  type SettleEntryWonInput,
  type SettleEntryLostInput,
  type SettleMarketInput,
  type SettleEventInput,
  type LockPoolInput,
  type CancelPoolInput,
  type ClosePoolInput,
  type ListSportsPoolsInput,
  type ListSportsEventsInput,
  type ListSportsMarketsInput,
  type ListSportsEntriesInput,
  type SportsPoolSummary,
  type SportsEventSummary,
  type SportsMarketSummary,
  type SportsEntrySummary,
} from './services/sports-pool-service';

// =====================================================================
// Approval Service 状态机 + 事件 + 错误 + 主体（Step 6 P1-1）
// =====================================================================

export {
  APPROVAL_TYPE,
  APPROVAL_REQUEST_STATUS,
  APPROVAL_STEP_STATUS,
  APPROVAL_APPLICANT_TYPE,
  APPROVAL_PRIORITY,
  APPROVAL_TYPE_RISK_LEVEL,
  APPROVAL_STEPS_BY_RISK,
  APPROVAL_DEFAULT_EXPIRES_HOURS,
  APPROVAL_DEFAULT_CHAIN_ID,
  APPROVAL_REQUEST_STATUS_TRANSITIONS,
  TERMINAL_APPROVAL_REQUEST_STATUSES,
  isValidApprovalType,
  isValidApprovalRequestStatus,
  isValidApprovalStepStatus,
  isValidApprovalApplicantType,
  isValidApprovalPriority,
  canTransitApprovalRequestStatus,
  isTerminalApprovalRequestStatus,
  getApprovalRiskLevel,
  getDefaultApprovalSteps,
  type FjnApprovalType,
  type FjnApprovalRequestStatus,
  type FjnApprovalStepStatus,
  type FjnApprovalApplicantType,
  type FjnApprovalPriority,
} from './services/approval-state-machine';

export {
  APPROVAL_EVENTS,
  APPROVAL_EVENT_SOURCES,
  type FjnApprovalEvent,
  type FjnApprovalEventSource,
  type ApprovalRequestCreatedPayload,
  type ApprovalStepDecisionPayload,
  type ApprovalRequestExecutedPayload,
  type FjnApprovalEventPayload,
} from './services/approval-events';

export {
  APPROVAL_ERROR_CODES,
  FjnApprovalError,
  ApprovalRequestNotFoundError,
  ApprovalRequestTypeInvalidError,
  ApprovalRequestStatusInvalidError,
  ApprovalRequestAlreadyDecidedError,
  ApprovalRequestExpiredError,
  ApprovalRequestNotPendingError,
  ApprovalRequestNotApprovableError,
  ApprovalRequestNotRejectableError,
  ApprovalRequestNotCancellableError,
  ApprovalRequestNotExecutableError,
  ApprovalRequestExecutedError,
  ApprovalStepNotFoundError,
  ApprovalStepStatusInvalidError,
  ApprovalStepAlreadyDecidedError,
  ApprovalStepNotCurrentError,
  ApprovalApproverRequiredError,
  ApprovalApproverDuplicateError,
  ApprovalApproverNotAuthorizedError,
  ApprovalApplicantRequiredError,
  ApprovalApplicantTypeInvalidError,
  ApprovalTitleRequiredError,
  ApprovalPayloadRequiredError,
  ApprovalPriorityInvalidError,
  ApprovalExpiresAtInvalidError,
  ApprovalTotalStepsInvalidError,
  ApprovalCurrentStepInvalidError,
  ApprovalStepsCountMismatchError,
  ApprovalCannotApproveOwnError,
  ApprovalSelfApprovalForbiddenError,
  ApprovalCannotCancelOthersError,
  ApprovalCommentRequiredForRejectError,
  type FjnApprovalErrorCode,
} from './services/approval-errors';

export {
  FjnApprovalService,
  createFjnApprovalService,
  type CreateApprovalRequestInput,
  type StartReviewInput,
  type ApproveStepInput,
  type RejectStepInput,
  type SkipStepInput,
  type CancelApprovalInput,
  type ExecuteApprovalInput,
  type EscalatePriorityInput,
  type ExpireApprovalInput,
  type ListApprovalRequestsInput,
  type ApprovalStepView,
  type ApprovalRequestView,
  type ApprovalRequestSummary,
} from './services/approval-service';

// =====================================================================
// Audit Service 状态机 + 事件 + 错误 + 主体（Step 6 P1-2）
// =====================================================================

export {
  AUDIT_MODULE,
  AUDIT_ACTION,
  AUDIT_REQUIRE_APPROVAL_MODULES,
  AUDIT_RISK_LEVEL,
  AUDIT_EXPORT_FORMAT,
  AUDIT_VERIFY_RESULT,
  AUDIT_HASH_ALGO,
  AUDIT_EXPORT_BATCH_SIZE,
  AUDIT_DEFAULT_RETENTION_DAYS,
  isValidAuditModule,
  isValidAuditAction,
  isValidAuditExportFormat,
  getAuditRiskLevel,
  isApprovalRequired,
  type FjnAuditModule,
  type FjnAuditAction,
  type FjnAuditExportFormat,
  type FjnAuditVerifyResult,
  type FjnAuditRiskLevel,
} from './services/audit-state-machine';

export {
  AUDIT_EVENTS,
  AUDIT_EVENT_SOURCES,
  type FjnAuditEvent,
  type FjnAuditEventSource,
  type AuditLogRecordedPayload,
  type AuditExportCompletedPayload,
  type AuditVerifyCompletedPayload,
  type AuditSuspiciousActivityPayload,
  type FjnAuditEventPayload,
} from './services/audit-events';

export {
  AUDIT_ERROR_CODES,
  FjnAuditError,
  AuditLogNotFoundError,
  AuditModuleInvalidError,
  AuditActionInvalidError,
  AuditOperatorIdRequiredError,
  AuditTargetTypeRequiredError,
  AuditTargetIdRequiredError,
  AuditBeforeValueRequiredError,
  AuditAfterValueRequiredError,
  AuditBothValuesRequiredError,
  AuditApprovalNoRequiredError,
  AuditApprovalNotFoundError,
  AuditApprovalNotApprovedError,
  AuditApprovalExpiredError,
  AuditIntegrityBrokenError,
  AuditIntegrityVerifyFailedError,
  AuditExportFormatInvalidError,
  AuditExportRangeInvalidError,
  AuditExportNotFoundError,
  AuditExportFailedError,
  AuditExportTooLargeError,
  AuditArchiveFailedError,
  AuditHashAlgoInvalidError,
  AuditChangeSummaryRequiredError,
  AuditLogRecordFailedError,
  AuditQueryRangeInvalidError,
  AuditRiskLevelInvalidError,
  type FjnAuditErrorCode,
} from './services/audit-errors';

export {
  FjnAuditService,
  createFjnAuditService,
  type RecordAuditLogInput,
  type RecordBatchInput,
  type QueryAuditLogsInput,
  type ExportAuditLogsInput,
  type VerifyIntegrityInput,
  type ArchiveAuditLogsInput,
  type AuditLogSummary,
  type AuditLogDetail,
  type AuditExportResult,
  type AuditVerifyResult,
  type AuditArchiveResult,
  type ObjectTimelineEntry,
} from './services/audit-service';

// =====================================================================
// Reporting Service 状态机 + 事件 + 错误 + 主体（Step 6 P1-4）
// =====================================================================

export {
  REPORT_TYPE,
  ALL_REPORT_TYPES,
  REPORT_PERIOD_GRANULARITY,
  REPORT_STATUS,
  REPORT_EXPORT_FORMAT,
  REPORT_VISIBILITY,
  REPORT_TRIGGER,
  REPORT_DEFAULT_EXPIRES_DAYS,
  REPORT_MAX_SUMMARY_DEPTH,
  REPORT_STATUS_TRANSITIONS,
  REPORT_TYPE_DEFAULT_GRANULARITY,
  REPORT_TYPE_DEFAULT_VISIBILITY,
  isValidReportType,
  isValidReportStatus,
  isValidReportPeriodGranularity,
  isValidReportExportFormat,
  isValidReportVisibility,
  isValidReportTrigger,
  isValidReportPeriod,
  inferPeriodGranularity,
  canTransitReportStatus,
  assertTransitReportStatus,
  isTerminalReportStatus,
  type FjnReportType,
  type FjnReportStatus,
  type FjnReportPeriodGranularity,
  type FjnReportExportFormat,
  type FjnReportVisibility,
  type FjnReportTrigger,
} from './services/reporting-state-machine';

export {
  REPORTING_EVENTS,
  REPORTING_EVENT_SOURCES,
  ALL_REPORTING_EVENTS,
  REPORTING_EVENT_COUNT,
  isValidReportingEvent,
  isValidReportingEventSource,
  type FjnReportingEvent,
  type FjnReportingEventSource,
  type ReportRequestedPayload,
  type ReportGenerationStartedPayload,
  type ReportGenerationProgressPayload,
  type ReportGenerationFailedPayload,
  type ReportReadyPayload,
  type ReportExpiredPayload,
  type ReportExportRequestedPayload,
  type ReportExportReadyPayload,
  type ReportExportFailedPayload,
  type ReportKeyMetricsUpdatedPayload,
  type ReportAnomalyDetectedPayload,
  type ReportChainReconciliationDonePayload,
  type ReportChainReconciliationMismatchPayload,
  type ReportArchivedPayload,
  type ReportingEventPayload,
} from './services/reporting-events';

export {
  REPORTING_ERROR_CODES,
  isFjnReportingErrorCode,
  getReportingErrorCodeCount,
  FjnReportingError,
  ReportTypeInvalidError,
  ReportTypeRequiredError,
  ReportPeriodInvalidError,
  ReportPeriodRequiredError,
  ReportGranularityInvalidError,
  ReportTriggerInvalidError,
  ReportVisibilityInvalidError,
  ReportExportFormatInvalidError,
  ReportNotFoundError,
  ReportAlreadyExistsError,
  ReportNoRequiredError,
  ReportStatusInvalidError,
  ReportNotReadyError,
  ReportExpiredError,
  ReportNotArchivableError,
  ReportArchiveFailedError,
  ReportVisibilityDeniedError,
  ReportGenerationFailedError,
  ReportExportFailedError,
  ReportDataSourceUnavailableError,
  ReportDataMissingError,
  ReportDataInvalidError,
  ReportSummaryInvalidError,
  ReportRequestedByRequiredError,
  ReportAnomalyThresholdInvalidError,
  ReportChainReconciliationMismatchError,
  type FjnReportingErrorCode,
} from './services/reporting-errors';

export {
  FjnReportingService,
  createFjnReportingService,
  type ListReportInput,
  type CreateReportInput,
  type GenerateReportInput,
  type ReportProgressInput,
  type FailReportInput,
  type CompleteReportInput,
  type ExportReportInput,
  type ChainReconciliationInput,
  type DetectAnomalyInput,
  type ArchiveReportInput,
  type SalesReportData,
  type PointsReportData,
  type FinanceReportData,
  type RiskReportData,
  type GenericReportData,
  type ChainReconciliationResult,
} from './services/reporting-service';

// =====================================================================
// 第 0 步-补齐：Identity Service 4 文件化（用户/钱包/推荐/设备）
//  - 文档：docs/工业级最终方案：Solana-first 统一生态架构.md §5.5.1
// =====================================================================

// Identity 状态机 + 工具
export {
  USER_STATUS,
  USER_TYPE,
  SESSION_STATUS,
  REFERRAL_RELATION_STATUS,
  DEVICE_BIND_STATUS,
  DID_BIND_STATUS,
  USER_STATUS_TRANSITIONS,
  DID_BIND_STATUS_TRANSITIONS,
  isValidUserStatus,
  isValidUserType,
  isValidSessionStatus,
  isValidReferralRelationStatus,
  isValidDeviceBindStatus,
  isValidDidBindStatus,
  canTransitUserStatus,
  canTransitDidStatus,
  assertTransitUserStatus,
  assertTransitDidStatus,
  isTerminalUserStatus,
  isTerminalDidStatus,
  isUserOperable,
  isUserLoginable,
  IDENTITY_DEFAULT_COUNTRY,
  IDENTITY_DEFAULT_VIP_LEVEL,
  IDENTITY_DEFAULT_USER_TYPE,
  IDENTITY_REFERRAL_CODE_LENGTH,
  IDENTITY_PASSWORD_MIN_LENGTH,
  IDENTITY_PASSWORD_MAX_LENGTH,
  IDENTITY_USERNAME_MIN_LENGTH,
  IDENTITY_USERNAME_MAX_LENGTH,
  IDENTITY_SESSION_DEFAULT_EXPIRES_HOURS,
  IDENTITY_REFRESH_TOKEN_DEFAULT_EXPIRES_DAYS,
  IDENTITY_MAX_LOGIN_ATTEMPTS_PER_HOUR,
  IDENTITY_MAX_DEVICES_PER_USER,
  IDENTITY_MAX_DID_PER_USER,
  type FjnUserStatus,
  type FjnUserType,
  type FjnSessionStatus,
  type FjnReferralRelationStatus,
  type FjnDeviceBindStatus,
  type FjnDidBindStatus,
} from './services/identity-state-machine';

// Identity 事件
export {
  IDENTITY_EVENTS,
  IDENTITY_EVENT_SOURCES,
  ALL_IDENTITY_EVENTS,
  IDENTITY_EVENT_COUNT,
  isValidIdentityEvent,
  isValidIdentityEventSource,
  type FjnIdentityEvent,
  type FjnIdentityEventSource,
  type UserRegisteredPayload,
  type UserLoginPayload,
  type UserLoginFailedPayload,
  type UserLogoutPayload,
  type UserUpdatedPayload,
  type UserStatusChangedPayload,
  type UserClosedPayload,
  type PasswordChangedPayload,
  type PasswordResetRequestedPayload,
  type PasswordResetCompletedPayload,
  type ReferralCodeGeneratedPayload,
  type ReferralBoundPayload,
  type ReferralUnboundPayload,
  // 与 Device Service 同名 payload 区分：Identity 版重命名
  type DeviceBoundPayload as IdentityDeviceBoundPayload,
  type DeviceUnboundPayload as IdentityDeviceUnboundPayload,
  type DidBoundPayload,
  type DidAnchoredPayload,
  type DidRevokedPayload,
  type VipLevelChangedPayload,
  type UserTypeChangedPayload,
  type SessionCreatedPayload,
  type SessionExpiredPayload,
  type SessionRevokedPayload,
  type SessionRotatedPayload,
  type IdentityEventPayload,
} from './services/identity-events';

// Identity 错误
export {
  IDENTITY_ERROR_CODES,
  isFjnIdentityErrorCode,
  getIdentityErrorCodeCount,
  FjnIdentityError,
  UserNotFoundError,
  UserAlreadyExistsError,
  UserStatusInvalidError,
  UserNotOperableError,
  UserNotLoginableError,
  UserClosedError,
  UsernameRequiredError,
  UsernameInvalidError,
  UsernameTooShortError,
  UsernameTooLongError,
  UsernameDuplicateError,
  EmailRequiredError,
  EmailInvalidError,
  EmailDuplicateError,
  PasswordRequiredError,
  PasswordTooShortError,
  PasswordTooLongError,
  PasswordIncorrectError,
  PhoneInvalidError,
  CountryCodeInvalidError,
  LoginFailedError,
  LoginAttemptsExceededError,
  SessionNotFoundError,
  SessionExpiredError,
  SessionRevokedError,
  SessionInvalidError,
  PasswordResetTokenInvalidError,
  PasswordResetTokenExpiredError,
  ReferralCodeInvalidError,
  ReferralCodeDuplicateError,
  ReferralRelationExistsError,
  ReferralRelationNotFoundError,
  ReferralCannotBindSelfError,
  ReferralBindExpiredError,
  DeviceNotFoundError,
  DeviceAlreadyBoundError,
  DeviceLimitExceededError,
  DidNotFoundError,
  DidAlreadyBoundError,
  DidLimitExceededError,
  DidInvalidError,
  DidPublicKeyMismatchError,
  DidAnchorFailedError,
  VipLevelInvalidError,
  UserTypeInvalidError,
  StatusChangeForbiddenError,
  CloseForbiddenError,
  SelfActionForbiddenError,
  type FjnIdentityErrorCode,
} from './services/identity-errors';

// Identity Service 主体
export {
  FjnIdentityService,
  createFjnIdentityService,
  type RegisterInput,
  type RegisterResult,
  type LoginInput,
  type LoginResult,
  type UpdateProfileInput,
  type ChangeStatusInput,
  type CloseUserInput,
  type ChangePasswordInput,
  type RequestPasswordResetInput,
  type RequestPasswordResetResult,
  type CompletePasswordResetInput,
  type BindReferralInput,
  // 与 Device Service 同名 input 区分：Identity 版重命名
  type BindDeviceInput as IdentityBindDeviceInput,
  type BindDidInput,
  type AnchorDidInput,
  type ChangeVipLevelInput,
  type UserSummary,
} from './services/identity-service';

// =====================================================================
// 第 0 步-补齐：Product Service 4 文件化重构（补充状态机/事件/错误导出）
//  - 文档：docs/工业级最终方案：Solana-first 统一生态架构.md §5.5.3
// =====================================================================

// Product 状态机 + 工具
export {
  STOCK_CHANGE_TYPE,
  PRODUCT_STATUS_TRANSITIONS,
  isValidProductStatus,
  isValidProductType,
  isValidStockChangeType,
  canTransitProductStatus,
  assertTransitProductStatus,
  isTerminalProductStatus,
  isPurchasable,
  isOnShelf,
  PRODUCT_DEFAULT_CURRENCY,
  PRODUCT_DEFAULT_TAX_MODE,
  PRODUCT_DEFAULT_STOCK,
  PRODUCT_MAX_PRICE,
  PRODUCT_MIN_PRICE,
  PRODUCT_NAME_MAX_LENGTH,
  PRODUCT_SUBTITLE_MAX_LENGTH,
  PRODUCT_DESCRIPTION_MAX_LENGTH,
  PRODUCT_GALLERY_MAX_COUNT,
  PRODUCT_BENEFIT_MAX_COUNT,
  PRODUCT_REGION_RULE_MAX_COUNT,
  PRODUCT_STOCK_MIN,
  PRODUCT_STOCK_MAX,
  PRODUCT_REVIEW_REQUIRED_FOR_ACTIVE,
  isValidProductPrice,
  isValidProductStock,
  isValidSaleWindow,
  type FjnStockChangeType,
} from './services/product-state-machine';

// Product 事件
export {
  PRODUCT_EVENTS,
  PRODUCT_EVENT_SOURCES,
  ALL_PRODUCT_EVENTS,
  PRODUCT_EVENT_COUNT,
  isValidProductEvent,
  isValidProductEventSource,
  type FjnProductEvent,
  type FjnProductEventSource,
  type ProductCreatedPayload,
  type ProductUpdatedPayload,
  type ProductVersionCreatedPayload,
  type ProductStatusChangedPayload,
  type ProductDeletedPayload,
  type ProductArchivedPayload,
  type StockAdjustedPayload,
  type StockDepletedPayload,
  type StockRestoredPayload,
  type ProductListedPayload,
  type ProductDelistedPayload,
  type ProductPausedPayload,
  type ProductResumedPayload,
  type ProductSoldOutPayload,
  type ProductSubmittedForReviewPayload,
  type ProductApprovedPayload,
  type ProductRejectedPayload,
  type BenefitAddedPayload,
  type BenefitRemovedPayload,
  type RegionRuleAddedPayload,
  type RegionRuleRemovedPayload,
  type RuleBindingAddedPayload,
  type RuleBindingRemovedPayload,
  type ProductEventPayload,
} from './services/product-events';

// Product 错误
export {
  PRODUCT_ERROR_CODES,
  isFjnProductErrorCode,
  getProductErrorCodeCount,
  FjnProductError,
  ProductNotFoundError,
  ProductAlreadyExistsError,
  ProductDeletedError,
  ProductArchivedError,
  ProductTypeInvalidError,
  ProductTypeRequiredError,
  ProductNameRequiredError,
  ProductNameTooLongError,
  ProductSubtitleTooLongError,
  ProductDescriptionTooLongError,
  ProductPriceRequiredError,
  ProductPriceInvalidError,
  ProductPriceOutOfRangeError,
  ProductCurrencyInvalidError,
  ProductTaxModeInvalidError,
  ProductStatusInvalidError,
  ProductStatusTransitionForbiddenError,
  ProductNotPurchasableError,
  ProductAlreadyActiveError,
  ProductAlreadyArchivedError,
  ProductStockInvalidError,
  ProductStockInsufficientError,
  ProductStockChangeTypeInvalidError,
  ProductActiveDeleteForbiddenError,
  ProductSaleWindowInvalidError,
  ProductNotInSaleWindowError,
  ProductRegionRuleConflictError,
  ProductRegionRuleLimitExceededError,
  ProductRegionRuleNotFoundError,
  ProductBenefitNotFoundError,
  ProductBenefitLimitExceededError,
  ProductBenefitTypeInvalidError,
  ProductBenefitAmountInvalidError,
  ProductRuleBindingNotFoundError,
  ProductRuleBindingInvalidError,
  ProductReviewRequiredError,
  ProductReviewReasonRequiredError,
  ProductGalleryLimitExceededError,
  ProductImageUrlInvalidError,
  type FjnProductErrorCode,
} from './services/product-errors';

// Product Service 主体（重导出，覆盖旧的单文件导出）
export {
  FjnProductService,
  createFjnProductService,
  type CreateProductInput,
  type CreateBenefitInput,
  type UpdateProductInput,
  type ListProductInput,
  type StockChangeInput,
  type AddBenefitInput,
  type RemoveBenefitInput,
  type AddRegionRuleInput,
  type RemoveRegionRuleInput,
  type AddRuleBindingInput,
  type RemoveRuleBindingInput,
  type ReviewProductInput,
  type ListProductWithRelationsInput,
} from './services/product-service';

// =====================================================================
// 第 0 步-补齐：Eco Power Service 4 文件新建（13 种算力分桶 + 释放计算源）
//  - 文档：docs/工业级最终方案：Solana-first 统一生态架构.md §5.5.5
// =====================================================================

// Eco Power 状态机 + 工具
export {
  POWER_TYPE,
  ALL_POWER_TYPES,
  POWER_TYPE_TO_ACCOUNT_FIELD,
  POWER_CHANGE_TYPE,
  POWER_SOURCE_TYPE,
  POWER_ACCOUNT_STATUS,
  POWER_ACCOUNT_STATUS_TRANSITIONS,
  POWER_SNAPSHOT_TYPE,
  isValidPowerType,
  isValidPowerChangeType,
  isValidPowerSourceType,
  isValidPowerAccountStatus,
  isValidPowerSnapshotType,
  canTransitPowerAccountStatus,
  assertTransitPowerAccountStatus,
  isTerminalPowerAccountStatus,
  isAccountOperable,
  isPositiveChangeType,
  isNegativeChangeType,
  POWER_DEFAULT_MEMBER_MULTIPLIER,
  POWER_DEFAULT_ACTIVITY_MULTIPLIER,
  POWER_DEFAULT_RISK_COEFFICIENT,
  POWER_MAX_MULTIPLIER,
  POWER_MIN_MULTIPLIER,
  POWER_MAX_AMOUNT,
  POWER_MIN_AMOUNT,
  POWER_LEDGER_PAGE_SIZE,
  POWER_SNAPSHOT_RETENTION_DAYS,
  POWER_LEDGER_RETENTION_DAYS,
  POWER_DEFAULT_EXPIRES_DAYS,
  POWER_FREEZE_AUTO_REVIEW_HOURS,
  POWER_NETWORK_TOTAL_DECIMALS,
  POWER_RATIO_DECIMALS,
  POWER_DEFAULT_VALIDITY_BY_TYPE,
  isValidPowerAmount,
  isValidMultiplier,
  type FjnPowerType,
  type FjnPowerChangeType,
  type FjnPowerSourceType,
  type FjnPowerAccountStatus,
  type FjnPowerSnapshotType,
} from './services/eco-power-state-machine';

// Eco Power 事件
export {
  ECO_POWER_EVENTS,
  ECO_POWER_EVENT_SOURCES,
  ALL_ECO_POWER_EVENTS,
  ECO_POWER_EVENT_COUNT,
  isValidEcoPowerEvent,
  isValidEcoPowerEventSource,
  type FjnEcoPowerEvent,
  type FjnEcoPowerEventSource,
  // 与 KYC Service 同名 payload 区分：Eco Power 版重命名
  type AccountCreatedPayload as PowerAccountCreatedPayload,
  type AccountStatusChangedPayload as PowerAccountStatusChangedPayload,
  type AccountClosedPayload as PowerAccountClosedPayload,
  type PowerGrantedPayload,
  type PowerConsumedPayload,
  type PowerExpiredPayload,
  type PowerAdjustedPayload,
  type PowerTransferredInPayload,
  type PowerTransferredOutPayload,
  type PowerReleasedConvertedPayload,
  type PowerFrozenPayload,
  type PowerUnfrozenPayload,
  type MemberMultiplierChangedPayload,
  type ActivityMultiplierChangedPayload,
  type RiskCoefficientChangedPayload,
  type EffectivePowerRecalculatedPayload,
  type SnapshotCreatedPayload,
  type ReleaseCalculationReadyPayload,
  type EcoPowerEventPayload,
} from './services/eco-power-events';

// Eco Power 错误
export {
  ECO_POWER_ERROR_CODES,
  isFjnEcoPowerErrorCode,
  getEcoPowerErrorCodeCount,
  FjnEcoPowerError,
  AccountNotFoundError,
  AccountAlreadyExistsError,
  AccountClosedError,
  AccountNotOperableError,
  AccountStatusInvalidError,
  AccountStatusTransitionForbiddenError,
  UserIdRequiredError,
  PowerTypeInvalidError,
  PowerTypeNotFoundInAccountError,
  PowerChangeTypeInvalidError,
  PowerSourceTypeInvalidError,
  PowerSnapshotTypeInvalidError,
  PowerAmountRequiredError,
  PowerAmountInvalidError,
  PowerAmountOutOfRangeError,
  PowerAmountZeroError,
  PowerInsufficientError,
  MemberMultiplierInvalidError,
  ActivityMultiplierInvalidError,
  RiskCoefficientInvalidError,
  MultiplierOutOfRangeError,
  LedgerNotFoundError,
  LedgerAmountInvalidError,
  SnapshotNotFoundError,
  SnapshotAlreadyExistsError,
  FreezeAmountInvalidError,
  FreezeReasonRequiredError,
  UnfreezeReasonRequiredError,
  TransferToSelfForbiddenError,
  TransferTargetAccountNotFoundError,
  ReleaseCalculationNotReadyError,
  ReleaseCalculationDuplicateError,
  ExpireDateInvalidError,
  SelfAdjustForbiddenError,
  RuleCodeRequiredError,
  RuleVersionInvalidError,
  InternalCalculationError,
  EffectiveRecalculationFailedError,
  type FjnEcoPowerErrorCode,
} from './services/eco-power-errors';

// Eco Power Service 主体
export {
  FjnEcoPowerService,
  createFjnEcoPowerService,
  // 与 Finance Service 同名 input 区分：Eco Power 版重命名
  type CreateAccountInput as CreatePowerAccountInput,
  type PowerAccountSummary,
  type ChangeAccountStatusInput as ChangePowerAccountStatusInput,
  type GrantPowerInput,
  type ConsumePowerInput,
  type AdjustPowerInput,
  type TransferPowerInput,
  type FreezePowerInput,
  type UnfreezePowerInput,
  type SetMemberMultiplierInput,
  type SetActivityMultiplierInput,
  type SetRiskCoefficientInput,
  type CreateSnapshotInput,
  type PrepareReleaseCalcInput,
  type ReleaseCalcResult,
  type ListLedgerInput,
  type PowerLedgerSummary,
  type PowerSnapshotSummary,
} from './services/eco-power-service';

// =====================================================================
// P1-5: Notification Worker —— 邮件/短信/Push/Webhook 异步分发
//  - 文档：docs/工业级最终方案：Solana-first 统一生态架构.md §5.5.9
//  - 通过 outbox 模式消费 fjn.notification.channel_dispatched 事件
// =====================================================================
export {
  FjnNotificationWorker,
  createFjnNotificationWorker,
  NOTIFICATION_WORKER_STATUS,
  NOTIFICATION_WORKER_DEFAULT_CONFIG,
  EmailChannelAdapter,
  SmsChannelAdapter,
  PushChannelAdapter,
  WebhookChannelAdapter,
  type FjnNotificationWorkerStatus,
  type NotificationChannelHandler,
  type NotificationDispatchPayload,
  type ChannelDispatchResult,
  type NotificationWorkerConfig,
  type ProcessOutboxEventInput,
  type ProcessOutboxEventResult,
  type ChannelAdapter,
} from './workers/notification-worker';

// ============================================================
// File Service（H038，文件对象 + 权限 + 访问审计 + 签名URL）
// ============================================================
export {
  FILE_STATUS,
  FILE_STATUS_TRANSITIONS,
  FILE_SENSITIVITY,
  FILE_TYPE,
  FILE_PERMISSION_TYPE,
  FILE_PERMISSION_STATUS,
  FILE_PRINCIPAL_TYPE,
  FILE_ACCESS_ACTION,
  FILE_ACCESS_RESULT,
  SIGNED_URL_ACTION,
  SIGNED_URL_STATUS,
  isValidFileStatus,
  isValidFileSensitivity,
  canTransitFileStatus,
  assertTransitFileStatus,
  type FjnFileStatus,
  type FjnFileSensitivity,
  type FjnFileType,
  type FjnFilePermissionType,
  type FjnFilePermissionStatus,
  type FjnFilePrincipalType,
  type FjnFileAccessAction,
  type FjnFileAccessResult,
  type FjnSignedUrlAction,
  type FjnSignedUrlStatus,
} from './services/file-state-machine';
export {
  FjnFileService,
  createFjnFileService,
  type CreateUploadTokenInput,
  type CompleteUploadInput,
  type CreateSignedUrlInput,
  type GrantPermissionInput,
  type RecordAccessInput,
  type ListFilesInput,
} from './services/file-service';